### PR TITLE
Notify My Android (NMA) Support

### PR DESCRIPTION
**Pull request by adalan**
Adding support for Notify My Android to latest (as of this pull) Sick-Beard.

### CODE REVIEW

**Comment by aaronflorey** [comment]
Has this been tested fully? because i'm getting python errors trying to run it.

 File "_opt_sickbeard_data_interfaces_default_config_notifications_tmpl.py", line 1273, in respond
NotFound: cannot find 'USE_NMA' while searching for 'sickbeard.USE_NMA'

**Comment by adalan** [comment]
I just installed from a Fresh pull without any issues. I've been running for months without issues.

**Comment by Weiry** [comment]
Adalan; I've installed your latest fork.
Now I get the update message saying: There is a newer version available (you're 4 commits behind)— Update Now...

When I press on update now I get an error:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/var/sickbeard/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/usr/local/var/sickbeard/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/local/var/sickbeard/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/usr/local/var/sickbeard/sickbeard/webserve.py", line 2116, in update
    updated = sickbeard.versionCheckScheduler.action.update() #@UndefinedVariable
  File "/usr/local/var/sickbeard/sickbeard/versionChecker.py", line 101, in update
    return self.updater.update()
  File "/usr/local/var/sickbeard/sickbeard/versionChecker.py", line 480, in update
    os.remove(new_path)
OSError: [Errno 13] Permission denied: '/usr/local/var/sickbeard/lib/pynma/pynma.py'

**Comment by adalan** [comment]
How did you install?

**Comment by Weiry** [comment]
Just a simple old, copy paste ;-)

**Comment by adalan** [comment]
I'm guessing that there is a file permission error due to the owner of the files when you created them. Can you check the permissions on the pynma folder and see if they are different from the other files?

**Comment by Weiry** [comment]
Yeah, I already checked that, the chmod on the folder and files is 755 and the owner is root

**Comment by aaronflorey** [comment]
[Errno 13] Permission denied: '/usr/local/var/sickbeard/lib/pynma/pynma.py'

The error states that permission denied for that folder, so what user is sickbeard running as? If not root, chown it to the user that runs it.

Or chmod -R 777 /usr/local/var/sickbeard/

**Comment by Weiry** [comment]
Thanks AzzABTN!

The chmod did the job!

But when I do:
chown -R sickbeard:user /usr/local/var/sickbeard/

I get this in return:
chown: unknown user/group sickbeard:user

I also checked:
cat /etc/passwd

And there I can see an account for sickbeard

how can I fix this, because I also get renaming errors with couchpotato and sabnzbd

**Comment by Weiry** [comment]
Found it!

I just had to type: chown -R sickbeard /usr/local/var/sickbeard/

**Comment by aaronflorey** [comment]
Glad you could get it sorted out!

I'm not sure why, but after some sort of time, the Enable NMA checkbox becomes unticked by itself and then won't send out notifications.

**Comment by adalan** [comment]
Any idea on how long? I just noticed that it happened, but I didn't notice how long before it happened.

**Comment by aaronflorey** [comment]
No idea!

**Comment by wezman** [comment]
Will this ever be part of the official release and if not, how do I install your patches so I can use NMA with Sickbeard?

**Comment by adalan** [comment]
I don't know if it's going to be pulled in, I nope so. In the meantime, if you just use my "fork". I will be keeping it up to do date with the main Sick-beard branch.

**Comment by wezman** [comment]
OK, I am running your fork now. :)  Thanks for the effort you have put in with this.

A few things.  The Test NMA button does not work in Chrome.  It works OK in Firefox.  Out of Interest, the Search Providers > Save Settings button also does not work in Chrome, so I suspect this is more related to a core JS file than something you have done.

I also noticed the Enabled check box for NMA unchecks itself too.  I have noticed this after restarting SickBeard.

cheers
Wes

**Comment by Weiry** [comment]
@wezman; I work with Chrome (17.0.963.46 m) and here everything works just fine...

@Adalan; When I restart SickBeard the checkbox for enable NMA is unchecked and I got a new error! ;-)

2012-02-12 12:56:33.336339 CHECKVERSION :: Unable to contact github, can't check for update

**Comment by wezman** [comment]
@Weiry That is odd, I am on 17.0.963.46 m too and I note that others have reported issues with saving in Chrome (the search providers settings).  On the NMA Save button, it does even start the spinning wheel when I click it. Are you on Win 7 too?

**Comment by Weiry** [comment]
@wezman; Saving works fine here and I'm also on Win 7 (ultimate, don't hink this maters ;-) )

When I press save changes I get (Configuration Saved /usr/local/var/sickbeard/config.ini) in less then a second.

**Comment by wezman** [comment]
@Weriy  There is a thread about it here (http://sickbeard.com/forums/viewtopic.php?f=4&t=2425) (this is where I got the idea to try Firefox).  Doesn't see to just be Chrome so must be something else.  Anyway, if you are not having the issue with this fork, then @Adalan can ignore my bug report. :)

**Comment by adalan** [comment]
I just restarted and noticed that it does indeed blow out the toggle to use NMA. It's still set in the config, so I must be missing the line that loads from the config. I'm looking into it now. 

I can also reproduce the Github connection issue, looking into that also.

I'm on Mac using the latest Chrome and I haven't had any issues with saving / loading.

Give me a few minutes to do some digging and i'll post up some patched.

**Comment by adalan** [comment]
I've just pushed an update that will correct the issue with NMA losing it's Enabled status.

**Comment by adalan** [comment]
Also now unable to reproduce the version check issue, every time I restart now, I'm getting a successful version check.

**Comment by Weiry** [comment]
Everything is working fine now!
Thanks Adalan!

**Comment by wezman** [comment]
FYI, I have a friend using the core release of Sickbeard and he has also been seeing the Github connection error recently when checking for an update.

**Pull request merged**
