### PR TITLE
Fixing issue 2404: Option to NOT rename .nfo to .nfo-orig

### PR DESCRIPTION
**Pull request by oldskool**
Adding a checkbox that allows the skipping of rename .nfo to .nfo-orig, as .nfo files aren't always used/created.

### CODE REVIEW

**Comment by lnhrdt** [comment]
@oldskool I wanted to say thanks for your work making this patch. I don't know if/when it will be accepted there but I cherry-picked your changes for a pull request into SickRage:
https://github.com/echel0n/SickRage/pull/608

**Comment by oldskool** [comment]
Updated the PR so the merge conflict is now resolved again.

**Comment by thezoggy** [comment]
you should rebase and force push this. not just pull... as it creates a dirty history

**Comment by oldskool** [comment]
@thezoggy Sorry about that, rebased now.

**Comment by CyberMew** [comment]
Has this been merged into the master branch? I am not seeing this option in the latest master branch.

**Comment by oldskool** [comment]
@CyberMew Nope, this has not been merged yet.

**Comment by oldskool** [comment]
@midgetspy any chance this can be merged? I keep on cherry-picking this locally :wink: 
If there are any problems with it, please let me know so I can fix them.

**Comment by oldskool** [comment]
After more than 5 years I don't think this will happen anymore 😄

**Comment by CyberMew** [comment]
This is no longer in active development, I think most have moved to use Sonarr.

**Comment by JackDandy** [comment]
This project is no longer active, perhaps try [SickGear](https://github.com/SickGear/SickGear) - you can drop in your existing sickbeard.db and continue with more features and search performance improvements.

p.s. This feature thread exists in SickGear as `Settings/Post Processing/File Handling/Rename .nfo file`

**Pull request closed without merging**
