### PR TITLE
fix: pp for files containing [ or ] while "Move associated Files" setting

### PR DESCRIPTION
**Pull request by lad1337**
for more info see http://code.google.com/p/sickbeard/issues/detail?id=1424

### CODE REVIEW

**Comment by Smenus** [comment]
Is this what e9cb8983264ca94be53af3c40a650eedef84de0a is for too? Does midget's fix work for you?

**Comment by lad1337** [comment]
jup it is. and miget's fix is even better it is in my branch allready

**Comment by Smenus** [comment]
Ah, sorry. Does that mean this can be closed?

**Comment by lad1337** [comment]
yes ! ... i was looking if i can close the request myself :) ... could not find it ... please close

**Pull request closed without merging**
