### PR TITLE
First step of converting db use to go through the PeeWee ORM library.

### PR DESCRIPTION
**Pull request by hobeone**
This is the first incremental step of converting SickBeard to use an ORM for it's database.  When finished it would allow mysql or postgres (in addition to sqlite) to be used as the DB.

This pull request adds the base models, tests and converts tv.py to use the new models.

This is my first time using github so let me know if I'm doing anything wrong.

### CODE REVIEW

**Comment by thezoggy** [comment]
new code would go in development not master. why peewee vs sqlalchemy or something else?

**Comment by thezoggy** [comment]
http://charlesleifer.com/blog/peewee-a-lightweight-python-orm/

**Comment by hobeone** [comment]
Can I change the target branch in this pull request or should I create a new one?

Looking over all of the Python ORMs I actually liked the Django one the most but I think you can't use that without using the whole framework.  SQLAlchemy seemed really heavyweight and required a bunch of setup where peewee took about 10 minutes to get going.

The Sickbeard use case is super simple so I don't think we'd need to use any of the advanced features of SQLAlchemy.

Also Peewee had this section on multi threaded apps:
https://peewee.readthedocs.org/en/latest/peewee/cookbook.html#multi-threaded-applications

I found a bunch of warnings about using SQLAlchemy with multithreaded cherrypy apps but I didn't dig into that too much.

**Comment by thezoggy** [comment]
you would have to submit a new branch.. as theres different code/changes in development not yet in master

**Pull request closed without merging**
