### PR TITLE
API support for JSONP

### PR DESCRIPTION
**Pull request by mattmelling**
Adds support to webapi for JSONP calls using the 'callback' or 'jsonp' request argument.

### CODE REVIEW

**Comment by piejanssens** [comment]
I understand what it enables you to do but could you sketch a situation where this could be useful?

Live UI for MediaFrontPage maybe?

**Comment by mattmelling** [comment]
It's useful for me as I'm writing a HTML/JS app to query the state of some services on my LAN from my phone's browser, and regular AJAX requests will not work because they will violate the origin policy. As you suggested a utility like MediaFrontPage could use JSONP to implement a live UI even if SB was running on a different machine. My app is already able to query SABnzbd and a couple of other services which are able to handle JSONP requests, but it would be excellent if it could query Sick Beard as well.

**Comment by gaetan-petit** [comment]
Very usefull!
Much cleaner and way more secure than : https://github.com/midgetspy/Sick-Beard/pull/358

**Comment by midgetspy** [comment]
Great, pulled into the development branch. In the future please just submit pull requests against development directly, thanks!

**Comment by mattmelling** [comment]
Fantastic, will do in the future.

**Pull request closed without merging**
