### PR TITLE
basic Nzbx support

### PR DESCRIPTION
**Pull request by ibawt**
I wrote some basic nzbx support.  I should be merged with the development branch. 

I'm adding support for things as they come in from the website dev, ( like tv rage indexes don't work 100% yet, probably have to modify the search parameters etc. )  It seems to work for me though.

I just modified the newsnab plugin to work with it.

Some of the files I believe my editor just changed to unix new lines.

### CODE REVIEW

**Comment by thezoggy** [comment]
you need to not change line endings.. makes finding what you changed difficult. also you should squash commits to clean things up

**Comment by ibawt** [comment]
Ok sounds good, I'm new at this github thing.  I have more to fix anyways, I'll pull request again when I've cleaned everything up.

**Comment by rasmuseeg** [comment]
Looking forward to this merge :+1:

**Comment by thezoggy** [comment]
This pull should be closed as Pull #567 should be used instead

**Pull request closed without merging**
