### PR TITLE
Issue 1629: Add full Synology index command set (addendum)

### PR DESCRIPTION
**Pull request by mreid-tt**
This amends the previous pull request #208 which added the complete 'synoindex' command library to Sick-Beard. The specific fix is to include the notifier for the creation of a new TV show.

### CODE REVIEW

**Comment by mreid-tt** [comment]
Hopefully this can get merged soon... very simple fix to close the one remaining item with Synology

**Comment by midgetspy** [comment]
Please re-submit a pull request for the development branch rather than master.

**Comment by Botono** [comment]
Since this pull request was never updated as requested in the last comment from midgetspy, I created this pull request:

https://github.com/midgetspy/Sick-Beard/pull/632

**Comment by mreid-tt** [comment]
Apologies for the lack of continuity on this request. The concept of this addendum was eventually submitted and merged under #591.

**Pull request closed without merging**
