### PR TITLE
Enhancment: Added Edit/Submit buttons to top of mass update page.

### PR DESCRIPTION
**Pull request by bungiman**
Makes it slightly easier to manage if the user has two places.

### CODE REVIEW

**Comment by bungiman** [comment]
Enhancement Screenshot

**Comment by bungiman** [comment]
So I think that this enhancment broke the bottom buttons. I am going to take a look. Happy to listen to any advice.

EDIT: Fixed!

**Comment by thezoggy** [comment]
that looks kinda funny.. what about putting them under the header? (aka 1st row). anyways.. why is this even needed? cant scroll to bottom (end key) ?

**Comment by bungiman** [comment]
For me I was sorting by something where all the shows of relevance were visible. Since I was mostly using the mouse to select my actions I found it was easier when I had access to the buttons at the top. In fact I kinda assumed they would be with the normal feel of SickBeard. I can certainly add it in as a row. Just wanted something put out.

**Pull request closed without merging**
