### PR TITLE
Changed Growl support to make it work with Growl 1.2 on Snow Leopard (10.6)

### PR DESCRIPTION
**Pull request by sHorst**
Hi,
i changed the Growl implementation to the Growl.info reference implementation. Which works over UDP and not TCP. 
BR
Stefan

### CODE REVIEW

**Comment by midgetspy** [comment]
Does this still work with Growl for Windows?

**Comment by sHorst** [comment]
haven't tried, since i do not have a windows but its the growl script from the growl.info svn so it should. i only commented the old code, so it can be changed with a flag, if it is not working any more

**Comment by sHorst** [comment]
just checked with the current version of growl for windows and it works as expected.

**Comment by sHorst** [comment]
some further infos to the windows/mac growl:

the udp version of the growl protocol is supported by both versions (but only basic messaging is working, but no images)
they both use different tcp protocols. (where images should work, but needs to do seperate implementation)

**Comment by nifoc** [comment]
Please note that once Growl 1.3 (for Mac) is released, the current implementation will "magically" start to work, since GNTP support is scheduled for 1.3.

**Comment by sHorst** [comment]
ok if that is so, than this patch is obsolete, do you know, when this update is scheduled? And for the time being I can use my Patch or use the gntp proxy

**Comment by nifoc** [comment]
Sorry, I don't know when version 1.3 will be released … all I know is that they talked about 1.3 for probably almost a year by now.

**Pull request closed without merging**
