### PR TITLE
Notify my android

### PR DESCRIPTION
**Pull request by JasonMillward**
I've added in a new notification type for Android users since none of the new ones focus on Android.

All credits go to Adalan, I've just used his changes in a recent branch.

### CODE REVIEW

**Comment by ps-taylor** [comment]
+1 for this merge

**Comment by flexd** [comment]
+5 :-)

**Comment by thezoggy** [comment]
is this pull request do the same thing as: https://github.com/midgetspy/Sick-Beard/pull/195 ?

**Comment by JasonMillward** [comment]
Yes, it is the same. Although in a more recent branch.

**Comment by adalan** [comment]
I'll close out my other pull to eliminate confusion.

**Comment by thezoggy** [comment]
went to test this.. not on amazon appstore.. only on android marketplace for 4.99!

**Comment by JasonMillward** [comment]
Unfortunately yes, however it seems to be the only push notification server that works for Androids

Notifo is closing down and hasn't worked for months (Myself and many forum users report on this)
Boxcar have been saying they'll have an android application out for months now, almost a year 
Prowl is a dedicated iOS application

If you're looking to test, I'm willing to fork out for a copy of NMA.

**Comment by flexd** [comment]
We could make our own? It's just based on Googles CDMA pushes.. You get about a bazillion of them (like 200k per day?) for free iirc.

**Comment by adalan** [comment]
I'd jump on that project. I looked into this not too long ago.

**Comment by willwhitworth** [comment]
I really hope this gets added soon!

**Comment by pokonski** [comment]
How about using Pusher and a dedicated app for android? It has free plan and everyone can register and supply their own API details = no global limits. There's a lib for receiving events https://github.com/EmoryM/Android_Pusher

**Comment by martynhaigh** [comment]
I'd be happy to help out with this - it's something I've been missing since Notifo stopped working.  I'm an android dev by trade, so more than happy to collaborate with anyone.

**Comment by flexd** [comment]
I can look into creating a service of or own. But notify my android isn't that bad. 

-------- Original message --------
Subject: Re: [Sick-Beard] Notify my android (#247) 
From: Martyn Haigh  
To: web@flexd.net 
CC:  

I'd be happy to help out with this - it's something I've been missing since Notifo stopped working.  I'm an android dev by trade, so more than happy to collaborate with anyone.--- Reply to this email directly or view it on GitHub:https://github.com/midgetspy/Sick-Beard/pull/247#issuecomment-3649629

**Comment by pokonski** [comment]
@martynhaigh could you experiment with receiving messages from Pusher? There's both libs for Android (to receive messages) and for Python (SickBeard) to send them http://pypi.python.org/pypi/pusher/0.5 :)

**Comment by martynhaigh** [comment]
Will have a look tonight - have you looked at the payment plans (https://app.pusherapp.com/plans)?  Do we have any stats on sick beard usage?

**Comment by pokonski** [comment]
Like I said, they offer a free sandbox plan with 100k messages per day. So everyone could just register a free account in Pusher and enter their own API key in SickBeard.

And 100k is a lot :)

http://pusher.com/pricing

**Comment by flexd** [comment]
There is a big difference between using something that requires a connection to a server for notifications VS Googles C2DM pushing notification. (i.e the difference between pull and push notifications).

**Comment by pokonski** [comment]
Can you elaborate? What difference is that for end-user?

**Comment by flexd** [comment]
If we have something on our phones that require us to keep connecting (polling) a server it will use more bandwidth. Isn't the whole idea of using C2DM that the phones will receive messages when they need them? 

If we are going to develop something of our own we might as well use http://code.google.com/android/c2dm/index.html (which FYI is what notifymyandroid uses).

I honestly don't see a need for developing yet another notification service when there are a ton existing ones. NMA charges for their android app but as far as I am aware that is simply to pay for their servers.

**Comment by pokonski** [comment]
Right, thanks for clarification ;)

**Comment by adalan** [comment]
I've been using NMA for a variety of different alerts and it's been working great. It's not super expensive and is a nice clean functional app.

**Comment by flexd** [comment]
I have the application myself. It costs around $5 and seems to work great. I haven't been using it for anything special yet though. The only negative thing is that I wish the server platform itself (as well as the app) was open source.

**Comment by JasonMillward** [comment]
I personally don't see the need to reinvent the wheel here, NMA works and has support for almost every language.

**Comment by tester22** [comment]
The NMA API is a complete ripof of the Prowl api:
http://nma.usk.bz/api.php
http://www.prowlapp.com/api.php

So maybe it would be better to simply add an option to Prowl to change the url from https://api.prowlapp.com/publicapi https://www.notifymyandroid.com/publicapi and it would work with current code.

**Comment by flexd** [comment]
Prowl does not exist for AndroidSent from Samsung Mobile 

-------- Original message --------
Subject: Re: [Sick-Beard] Notify my android (#247) 
From: Anton  
To: web@flexd.net 
CC:

**Comment by tester22** [comment]
But NMA has designed their API as a copy of the Prowl api, so there is no need to add more code to SB just an option to change the url for the NMA users.

**Comment by flexd** [comment]
Ah... Well that's nice then. Until they decide to change something.

**Comment by willwhitworth** [comment]
While allowing an option to change the URL would fix it for most, I do not see this as the best solution. In my case, I use an Android phone and my brother uses an iPhone. Since we share the same instance of sabnzbd, we would like to both be notified of downloaded shows. This would not be possible if we had to choose which URL for Prowl to use. I believe that NMA should replace Notifo in Sickbeard since it is being shut down anyway.

**Comment by flexd** [comment]
I agree. Notifo is dead, NMA is not. Prowl and NMA are not the same so they should not be the same notification plugin.

**Comment by Weiry** [comment]
+5!

Please add NMA to Sickbeard!

**Comment by RobLoach** [comment]
> The NMA API is a complete ripof of the Prowl api

It's not that NotifyMyAndroid API rips off of the Prowl API. It's meant to be compatible so that the adaption of it is easier to manage. Although I haven't used it before, [PyNMA](https://github.com/uskr/pynma) seems very promising. Either way, I'm a big +1.

**Comment by Thermionix** [comment]
+1

**Comment by aaronflorey** [comment]
PLEASE add this!

Is there anyway we can use this now?

**Comment by adalan** [comment]
This afternoon I'm going to be forking and running a parallel branch which will include current and include my addition until this get's merged.

**Comment by willwhitworth** [comment]
Excellent. Will you update us here when it's ready so we can try it?

**Comment by adalan** [comment]
You got it.

**Comment by adalan** [comment]
Ok, fork is here: https://github.com/Adalan/Sick-Beard

I'll submit another Pull Request to see if we can finally get this added, but untill then, I'll keep this updated.

**Comment by adalan** [comment]
New Pull request: https://github.com/midgetspy/Sick-Beard/pull/293

**Comment by Weiry** [comment]
Adalan; I've installed your copy of Sickbeard, I see the options for NMA and I configured everthing.
After I saved the settings I pressed on Test NMA, after that the wheel keep on turning and I don't get a test message.
What could this be?

Thanks

**Comment by adalan** [comment]
Let me check, I had this issue in the past.

**Comment by aaronflorey** [comment]
Untill this pull request is pushed through, everyone using this fork will have the header saying they need to update from the main repo, do you mind if i put in a pull request changing the url to check for updates to your fork?

**Comment by aaronflorey** [comment]
I also get the same error as Weiry, it's because the test button is calling the wrong url or something is not working.

GET http://xxxxxx:9091/home/testNMA?nma_api=xxxxxxxxxxxxx&nma_priority=0 404 (Not Found)

**Comment by adalan** [comment]
That should be working now, I forgot a couple lines off code. :-/ Sorry about that!

**Comment by aaronflorey** [comment]
no worries, I made a pull request with the fix, and the url changes

**Comment by Weiry** [comment]
AzzABTN; I've installed your copy and restarted Sickbeard, but now it won't start :-(

**Comment by flexd** [comment]
In case you haven't noticed: It seems this has now been implemented in Sickbeard! Works for me and I've just updated the normal way :-)

**Comment by Weiry** [comment]
Very cool :-)

**Comment by ps-taylor** [comment]
this rocks - thanks guys, awesome stuff!

**Comment by JasonMillward** [comment]
Since it's in, this is no longer needed.

**Pull request closed without merging**
