### PR TITLE
Added provider for nzbX.

### PR DESCRIPTION
**Pull request by jrdnull**
Provider for nzbX, discussed with thezoggy and Lemon in irc.

Let me know of any changes/improvements and I'll fix them.

### CODE REVIEW

**Comment by thezoggy** [comment]
This is good to go.

**Comment by midgetspy** [comment]
This code seems to work well but the provider itself is providing junk results. I won't be pulling it for now, hopefully we can figure out a way to exclude results like these:

[Desktop]-[1/1] - "europolis.2010.pdtv.x264-saftoiu.nfo.nzb"
[o4u] "Melissa & Joey.s01e01.Pilot.dTV.x264-o4u.vol07+08.PAR2"
Scary.Walls.(08-10-12).PDTV.XviD-acrwt

(and before somebody asks: no SB won't add parsing rules to parse the raw post names, that's the entire point of the indexer)

**Comment by LemonadeDev** [comment]
I've found the issue, the API is returning spam flagged results to you (as seen by the spam: 1 attribute). I'll have these hidden in the next couple of minutes.

**Comment by LemonadeDev** [comment]
Appears there was an issue with the "recent" code when using more than one category, I have now fixed this.

**Comment by thezoggy** [comment]
ty lemon

**Comment by jrdnull** [comment]
Have you had a chance to look at this again midgetspy?

**Pull request merged**
