### PR TITLE
Added proper-finding to BTN

### PR DESCRIPTION
**Pull request by genial123**
Implemented the previously non-existing findPropers() to BTN provider. Cannot use OR-operator in the API's release-field, so two API-calls are needed.

### CODE REVIEW

**Comment by mr-orange** [comment]
The findPropers() is implemented in generic provider. Why are you redefing this?

**Comment by genial123** [comment]
From what I could see that was how it was done in the other providers, so thought that was the preferable way of doing it. If not, where should I place it?

**Comment by thezoggy** [comment]
you subclass the generic provided functions if the generic functions dont do what you want

**Comment by thezoggy** [comment]
This can be closed, this was handled under Pull #713

**Pull request closed without merging**
