### PR TITLE
Renaming subtitles when renaming episodes. 

### PR DESCRIPTION
**Pull request by tomelfring**
This commit will rename all *_.srt files where *_ is a country code
specified in the ISO693-1 language codes.

Addresses:
http://code.google.com/p/sickbeard/issues/detail?id=1698
http://code.google.com/p/sickbeard/issues/detail?id=1805

This time for the development branche.

### CODE REVIEW

**Comment by jurrabi** [comment]
I see this is not merged in master. Any reason? Seems like a good idea for many people...

**Comment by jurrabi** [comment]
I just tested tommy101 version and at least it renames my ep.es.srt files. It's doesn't keep the .es.srt part (renames to just .srt) and that's a shame since I usually have .es and .en files... I guess I'll take a look myself.

What I'm sure is that more people will benefit from this in master...

**Comment by LordZepto** [comment]
:+1: I was trying to do the same. I usually have ep.es.srt and ep.en.srt

**Comment by tomelfring** [comment]
So you say some-episode-name.es.srt is not renaming properly?

**Comment by jurrabi** [comment]
I took a look 3 weeks ago and got partial success. Básically the issue (well, I wouldn't call it issue since it was designed that way) is split in several routines and I only caught one. But since I had already run my masive renaming I didn't kept looking.

I'm at work now and don't have access or remember what I found out, but I'l try to share later today.

**Comment by thezoggy** [comment]
can you rebase your submission, we modified how sickbeard detects the extension (to support multi dot ones). I think it this may not even be needed now because of it..

**Pull request closed without merging**
