### PR TITLE
Added pytivo notifcations

### PR DESCRIPTION
**Pull request by gordonturner**
A pytivo notifier has been added, this will allow Sick-Beard to trigger an upload of the video to a Tivo box.

### CODE REVIEW

**Comment by kbgators** [comment]
Any luck getting this added to the main app

**Comment by gordonturner** [comment]
Nope, no luck :-(

**Comment by thezoggy** [comment]
can you update/rebase this off master, there have been a bit of changes.

**Comment by gordonturner** [comment]
@thezoggy I have rebased, tested and pushed to my fork of Sick-Beard, should be easier to merge now.

Please let me know if there are any questions about the code?

**Comment by kbgators** [comment]
Kind of a newbie here, is this pytivo notification now in midgetspy master version?
Love this pytivo fucntionality!

**Comment by thezoggy** [comment]
you should not work in your 'master' branch. it makes your history clutter and dirty. create a branch with your changes.

**Comment by gordonturner** [comment]
@thezoggy still learning 'the git' way of doing things, thanks.

Is branching a requirement to a successful pull request, or just best practice? 

(ie should I close this request, branch and re-request?)

**Comment by thezoggy** [comment]
i would close this request and resubmit personally. you can do it without rebsubmitting but if your new to git i wont get into the details as its a bit confusing (cherry picking / rebase / rename)

**Comment by gordonturner** [comment]
K, will be closing this request and resubmitting shortly.

**Comment by gordonturner** [comment]
New pull request done via a branch, I think I got it right.

https://github.com/midgetspy/Sick-Beard/pull/268

@kbgators sorry, missed your question, when the new pull request has been completed, then it will be in the implementation.

**Pull request closed without merging**
