### PR TITLE
Add omgwtfnzbs as a rss provider

### PR DESCRIPTION
**Pull request by imajes**
backlog support later, but for now this will get basic rss support. (commit is now squashed.)

### CODE REVIEW

**Comment by thezoggy** [comment]
can you rebase this off current development? and any update on adding backlog support?

**Comment by imajes** [comment]
@thezoggy: i'm gonna work on improving support on this today. lets try and get it landed. I'm finding out about backlog support

**Comment by thezoggy** [comment]
Any chance getting an invite so we can test with it?

-----Original Message-----

**Comment by imajes** [comment]
@thezoggy: what email should i get it sent to?

**Comment by omgwtfnzbs** [comment]
sent, just send us a staff pm mate and will sort ya out with an apikey to test with.

**Comment by imajes** [comment]
closed/replaced by #557 :+1:

**Pull request closed without merging**
