### PR TITLE
Fix wrong sql for coming soon page

### PR DESCRIPTION
**Pull request by greenythebeast**
See http://sickbeard.com/forums/viewtopic.php?f=4&t=7160 for explanation. Forgive me if I did the pull request incorrectly; I've never used GitHub before!

Credit to Prinz23!

### CODE REVIEW

**Comment by Conjuro** [comment]
That's a lot of commits for just two altered lines, might wanna consider a squash and force push.

**Comment by greenythebeast** [comment]
Like I said in the original request, I've never used GitHub before. I will do some research and figure out how to do what you suggested!

**Comment by thezoggy** [comment]
?

**Comment by greenythebeast** [comment]
I was messing around with my repo and forgot that any change I make goes into the pull request. If I have time I'll resubmit the original request.

**Pull request closed without merging**
