### PR TITLE
Add 1080p and RawHD qualities to SB

### PR DESCRIPTION
**Pull request by thezoggy**
- Added 1080p aired, 1080p web-dl, 1080i/720p mpeg2 (Raw) qualities
  - Adjust CSS/sorting routines to reflect changes, updated quality tags.
  - Added `.ts` to be assumed RawHD quality
- Removed 'unknown' as a possible archive quality from the qualityChosser/sb-api/apibuilder
  
  >  As this creates an bad scenario where an 1080p bluray appear as 'low quality' or even worse could get replaced by some crap mobile friendly release because of 'unkown' having a higher internal value.
- SB searches by just the show name if the show has only one season which makes sense until the results contain more than the rss feed limit.
  
  >  If a show (ex: 'Terra Nova') has 10+ episodes.. so if each ep really came out in the 9 possible qualities (then there is also proper/repacks).. you can easily get over 50 results searching for the show name.. so I added a hack that restores using the S##E## if the show is only one season and has less than 11 episodes total.
- Show `missing.png` on the history page if the provider that was previously used and is no longer in SB/config (deleted/legacy).

### CODE REVIEW

**Comment by mtakacs** [comment]
+1 , was hoping this was on deck somewhere..

**Comment by pokonski** [comment]
7a9

**Comment by mtakacs** [comment]
nice duck!

**Comment by nberlee** [comment]
@thezoggy Netflix only series like the House of Cards have WEBrip, which I think should be treated as web.dl in sickbeard

**Comment by thezoggy** [comment]
This is already discussed internally.. And will be handle post merge

-----Original Message-----

**Comment by mtakacs** [comment]
> This is already discussed internally.. And will be handle post merge

awesome!  Can't wait for this to land.  :)

**Comment by marcusds** [comment]
> awesome! Can't wait for this to land. :)

Seconded!

**Comment by junalmeida** [comment]
Will this ever be merged?

**Comment by Skindred** [comment]
The code has been tested, and found stable, in many other peoples forks.
I think that the time has arrived to merge this.
But that's what I think :)

**Comment by nifoc** [comment]
The lack of communication on this, once again, makes me a really sad panda.

If something is not okay with this PR, why not let people know so that the community is able to help?

**Comment by thezoggy** [comment]
People have lives. And dev telated talk happens internally on IRC.. Not on github.

-----Original Message-----

**Comment by nifoc** [comment]
> People have lives.

Which is why OSS is so great. The community can help and not take away too much time from one developer. But …

> And dev telated talk happens internally on IRC

… is kinda working directly against this. I bet I'm not the only one who would love to help make SickBeard even better, but I'm not _really_ able to, or am I?

**Comment by nberlee** [comment]
This kind of unopeness is a reason for me never to open a pull request here again like I did a few times in the past.  This cuts people off,  and really doesn't motivate them to participate in any way.

**Comment by enigma2k** [comment]
what's a good fork with frequent updates that has this already included?

**Comment by simonk83** [comment]
Pretty much.  As I've said before, SB isn't really an open project as
others are, it's more of a dictatorship really :).  Not to take anything
away from the 3 or so devs that make all the decisions, as SB is generally
nice and stable, however I do think its nowhere close to being as good as
it could be as the majority of the most popular and requested pull requests
are left to idle as one of the few people with decision making abilities
decides its "not important to them" or whatever.

Again, I love the app, it's amazing, but the work ethic behind it is all
wrong IMO.

**Comment by thezoggy** [comment]
there are several forks.. there are several people that have taken it upon themselves to take sb in the direction they want. yes, midget's repo is solely controlled by him and no one else can push out updates... but honestly most people wouldnt be qualified to push out updates as there is a lot of spaghetti code that only he knows/understands/wrote. even on some of the most simple pull requests people have broken parts of sb because they were not paying close enough attention or knew how python worked. my comments were not to push people way but to set expectations. recently we've had a number of people willing to contribute and ive worked with them personally to get things updated and fixed (nzbsrus/nzbx.co/etc) now the ball is in midget's court to code review/accept them. which is going to have to be on his time since well.. it is his repo after all. if i break something.. he has to deal with the cleanup... so one could hope you would see why hes a bit careful on including code.

**Comment by mtakacs** [comment]
@thezoggy thanks for the glimpse into the behind-scenes-workings...

**Comment by midgetspy** [comment]
Pulled

**Comment by nifoc** [comment]
So, how long does it usually take for the development branch to be merged back into master?

**Comment by thezoggy** [comment]
generally we try to stick to a 1month cycle. we are running a little behind but are working on updates if you havent noticed :)

**Comment by madburg** [comment]
Will this "Add 1080p and RawHD qualities to SB" make it into the Windows binary soon? It would be most appreciated. Thanks for all your work!

**Comment by thezoggy** [comment]
just keep an eye out on the changelog for whats in dev (which is whats going to be in the next windows binary)
https://github.com/midgetspy/Sick-Beard/wiki/ChangeLog

**Comment by madburg** [comment]
Thanks for the reply back! So its not there yet in dev, or am I missing something? This one is dear to my heart as so much is coming in 1080p WEB-DL and a few shows that only come in RAW. Appreciate all that you can do to make this happen and make its way to the win binary. Nothing short of an awesome app!

**Comment by joel-daros** [comment]
Definitely needs a setting for the 1080p WEB DL

**Comment by thezoggy** [comment]
@MrSparklle 1080p web-dl is there.. along with 1080p hdtv and 720p/1080i rawhd (mpeg2)

**Comment by madburg** [comment]
Cant wait for the new Windows Build, thanks thezoggy!

**Comment by nifoc** [comment]
It's been another three weeks: Anything on when the next master<-development merge will happen?

**Comment by midgetspy** [comment]
Probably within a week or so.

**Pull request closed without merging**
