### PR TITLE
Added Boxcar2 Notifier

### PR DESCRIPTION
**Pull request by mongo527**
Added Notifier for Boxcar2.
Boxcar2 uses Access Token instead of username/email.

### CODE REVIEW

**Comment by rolo20** [comment]
Thanks! It's working.

**Comment by andy-g** [comment]
Any reason why this hasn't been merged in yet?

**Comment by sl33kr** [comment]
I have some code that I would like to be able to submit for this that also allows the user to select a sound to play on notification.

**Comment by mongo527** [comment]
Heads up! Boxcar v1 end of life is July 1st.
If this can be merged before then, that would be awesome!

Thanks

**Comment by mremond** [comment]
I am from Boxcar team. Please, let us know if there is anything we can do to help to have Boxcar 2 support in main Sickbeard branch.

**Comment by thezoggy** [comment]
@mremond boxcar2 support will be added under https://github.com/midgetspy/Sick-Beard/pull/847

**Pull request closed without merging**
