### PR TITLE
Issue 1629: Add full Synology index command set

### PR DESCRIPTION
**Pull request by mreid-tt**
This attempts to add the complete 'synoindex' command library to Sick-Beard as well as function calls for existing I/O operations in the PVR app, namely creating folders as well as adding and removing files from the library.

### CODE REVIEW

**Comment by mreid-tt** [comment]
Added proposed code to deal with downloading higher quality files (MKV versus AVI) for which Sick Beard replaces and causes duplicate index entries on the Synology media server

**Comment by midgetspy** [comment]
FYI your line endings are unix style, the SB code is windows-style.

**Comment by mreid-tt** [comment]
I'm not sure how to change my line breaks. I edited the code via the web interface in Safari... any thoughts or advice on what or how to fix?

**Comment by midgetspy** [comment]
I can fix it when I pull it. Does the synology never do these things itself (removing old files or finding new ones)? Seems like a lot of overhead for SB to be telling it every change it makes to the filesystem (thinking specifically of renames and the upcoming feature that can sort eps into many sub folders...)

**Comment by mreid-tt** [comment]
Thanks... as for Synology, I'm guessing that the operations are necessary to keep the media index in sync. If you do these things via the built-in file browser it does update the index so I'm guessing that it also has to execute these commands. My guess is that the file commands are interacting with the core OS and the media server is not part of it. If you would consider a suggestion that perhaps all I/O functions can be moved to a separate library which can be used separately as an abstraction. That way it can be modified as needed for all the various idiosyncrasies that may exist out there. Alternately, we can probably send an email to Synology support for their input...

**Comment by midgetspy** [comment]
Is there a command to remove a folder?

**Comment by mreid-tt** [comment]
Yes, this was detailed in the issue you merged at http://code.google.com/p/sickbeard/issues/detail?id=1676.
I can update my code to use all the defined commands if you wish...

**Comment by mreid-tt** [comment]
I think I've updated all the Synology code to take advantage of the complete syntax. This way your future code which may rely on this can have all the commands ready to go in a standardised form.

**Comment by mreid-tt** [comment]
Considering the previous update, I've updated the remainder of notifier code to be a collection of wrapper functions to reduce the amount of code duplication

**Comment by mreid-tt** [comment]
I believe the pull request is as clean and as correct as I can make it. Do let me know if there is anything else I need to look at before this can be merged with the main code... eager to see this in action...

**Comment by ballan91** [comment]
+1 for this, I've been using these modifications for over a week now with no real issues. It's nice to finally have everything show up in the media index!

**Comment by mreid-tt** [comment]
@ballan91 - Thanks for testing it, not too familiar with doing that on my NAS. I was most interested in knowing the result of three scenarios:
(1) Creating a new show - shows up in index?
(2) Downloading new season - shows up in index?
(3) Upgrading SD show to HD (i.e. AVI to MKV usually) - do the previous downloads get removed from the index? (i.e. are there duplicate episodes in the index?)

If all of these things work as expected then I really hope the authors merge this pull request as it will really benefit us Synology users.

**Comment by ballan91** [comment]
@houndtt - Thanks for writing it!
In all three scenarios the media index is updated appropriately. 

I really hope that the authors can work to merge this request as it will definitely make the experience for all Synology users much more seamless. It's a pain having to manually add folders to the index every time I add a new show or a new season...

**Comment by mreid-tt** [comment]
@ballan91 - Excellent! Now we just have to get this code merged... Any way to petition the admins to somehow bring some closure to this?

**Comment by Diaoul** [comment]
+1 for this

**Comment by damselem** [comment]
+1

**Comment by midgetspy** [comment]
Pulled into SB development branch, where all changes will now sit until they get pulled to master as "stable".

**Comment by mreid-tt** [comment]
Now that this has been merged, I realise that one of the three tests was not working... (create new shows). A such, I've created a new pull #391 to close this hole. Hopefully it will get merged soon.

**Comment by mreid-tt** [comment]
The final addendum contained in pull request #591 was merged into the master and should now allow the original issue to close

**Pull request closed without merging**
