### PR TITLE
Add custom Torrent RSS providers

### PR DESCRIPTION
**Pull request by domaslasauskas**
Allows adding torrent RSS feeds as custom search providers.

### CODE REVIEW

**Comment by thezoggy** [comment]
Is this just the completion of the code from: https://github.com/midgetspy/Sick-Beard/tree/custom_torrents ?

**Comment by domaslasauskas** [comment]
I haven't seen that branch yet. I did my branch this morning from scratch following how custom newznab providers were implemented. I'll have a look at https://github.com/midgetspy/Sick-Beard/tree/custom_torrents <del>tomorrow</del>, thanks

**Comment by domaslasauskas** [comment]
I've looked over the changes in [custom_torrents](https://github.com/midgetspy/Sick-Beard/tree/custom_torrents) branch—it's quite old. But it seems that I did it in a similar fashion. Let me know if I should update my pull request in any way.

**Comment by mr-orange** [comment]
You should insert a proper check after inserting RSS Feed url to see if you can obtain a valid rss from the url and if you can parse correctly the item. If you want you can take this check code from my tpb branch.

**Comment by Stanzilla** [comment]
any progress here?

**Comment by domaslasauskas** [comment]
Sorry, was busy with other things. I'll pick this one up next week.

**Comment by elranu** [comment]
:+1:  This feature will be cool

**Comment by trapper-** [comment]
I would love this feature too.

I did try the old custom_torrents branch, but it is very old.

**Pull request closed without merging**
