### PR TITLE
Notify My Android (NMA) Notification Implementation

### PR DESCRIPTION
**Pull request by adalan**
I've implemented Notify My Android as another notification option.

### CODE REVIEW

**Comment by itsmegb** [comment]
sweet, i was about to do this, as i'd already done one for Couchpotato. Glad you beat me to it though!

**Comment by adalan** [comment]
It was your addition to Couchpotato that got me excited about NMA.  :-)

**Comment by justyns** [comment]
Awesome, I was also going to implement this and decided to look around to see if anyone else has first.  Thanks :)

**Comment by bjeanes** [comment]
+1

**Comment by adalan** [comment]
Anything I can do to expedite this pull?

**Comment by khellang** [comment]
When can we expect this pull request to be accepted? Would be a great addition :)

**Comment by vledder** [comment]
would love this feature! +1

**Comment by pritchag** [comment]
Please pull! Excellent addition...!

**Comment by ghost** [comment]
+1, now that notifo is closing down something to talk to Android phones would be much appreciated.

**Comment by SHammoud** [comment]
+1 for NMA

**Comment by willwhitworth** [comment]
Can't wait to see this implemented!

**Comment by chibani** [comment]
Any news about the pull ?

**Comment by JasonMillward** [comment]
I recreated the branch with the latest updates, since you wont be able to merge on such an old branch.

All credits go to Adalan.

https://github.com/midgetspy/Sick-Beard/pull/247

**Comment by ps-taylor** [comment]
+1 for NMA

**Comment by adalan** [comment]
Jason, thanks for the update!

**Comment by thezoggy** [comment]
does this pull request do the same thing as: https://github.com/midgetspy/Sick-Beard/pull/247 ?

**Pull request closed without merging**
