### PR TITLE
Added Pushalot Notifier

### PR DESCRIPTION
**Pull request by molesinski**
Just like Notify My Android and Pushover on Android and iOS, this adds support for push notifications on Windows Phone and Windows 8 clients.

### CODE REVIEW

**Comment by rowdynl** [comment]
Does this still work with the newer versions? I really want this, so before I break my current install..

**Comment by molesinski** [comment]
I actually have no idea, since I do not use SickBeard myself. 11 months ago it was pretty straightforward adding this.

**Comment by rowdynl** [comment]
Still does, with just a little modification for saving the settings.. :)

**Comment by thezoggy** [comment]
i have this slated to be included in a branch im working on... (updating several notifiers)

**Comment by rowdynl** [comment]
Great! Maciej's code works flawlessly, with just a few adjustments in **sickbeard/webserve.py**. The code in the other files don't need to be adjusted.

In the code from Maciej, **sickbeard/webserve.py**, lines **1363** to **1377** can be discarded, and lines **1464** to **1468** can be replaced by this

```
sickbeard.USE_PUSHALOT = config.checkbox_to_value(use_pushalot)
sickbeard.PUSHALOT_NOTIFY_ONSNATCH = config.checkbox_to_value(pushalot_notify_onsnatch)
sickbeard.PUSHALOT_NOTIFY_ONDOWNLOAD = config.checkbox_to_value(pushalot_notify_ondownload)
sickbeard.PUSHALOT_AUTHORIZATIONTOKEN = pushalot_authorizationtoken
```

**Comment by rowdynl** [comment]
thezoggy, sorry to ask, but any idea on a timeframe when it's included?
Or, wich branch, then I'll fork it and create a pull request into your branch..?

**Comment by thezoggy** [comment]
this can be closed, as freshly updated code has been submitted under https://github.com/midgetspy/Sick-Beard/pull/848

**Pull request closed without merging**
