### PR TITLE
DailyTvTorrents Provider (Updated Version)

### PR DESCRIPTION
**Pull request by dzerovibe**
- RSS feed downloading works
- RSS feed parameters can be user-configured (quality preferences, minimum age, wait time, norar, and single)
- Backlog search works
- Converted provider image gif to png
- Proper handling of different versions of show names in the back end

### CODE REVIEW

**Comment by mr-orange** [comment]
I'm using this provider (the old version) in my fork and I can say that it is a really good torrent provider. If merged in sickbeard-master the torrent snatching handling will be a lot better imho.

**Comment by dzerovibe** [comment]
As mr-orange said, I find DailyTvTorrents to be a very good feed provider for torrents. I came across their site several months ago when I became frustrated with all the apparent problems with EZRSS downtime. I switched to using DailyTvTorrents, but since SB doesn't support their feed, I basically stopped using SB for snatching, and just let it handle the post-processing. I was having to download the torrents manually. I'd been meaning for a long time to try to get DailyTvTorrents to work in SB, and I finally got around to giving it a try. I'm glad I did, and now I have fully automated downloads working again, with the added bonus of being fairly confident that I will be getting good quality torrents.

**Comment by obiesmans** [comment]
That's a shame, any chance of a re-opening ?

**Comment by mr-orange** [comment]
Dtt is offline. Sadly this pull request is Useless in this moment.

Il giorno 05/mag/2013, alle ore 12:00, obiesmans notifications@github.com
ha scritto:

That's a shame, any chance of a re-opening ?

—
Reply to this email directly or view it on
GitHubhttps://github.com/midgetspy/Sick-Beard/pull/606#issuecomment-17449522
.

**Comment by dzerovibe** [comment]
Yup, as mr-orange said, DTT has gone offline, and the owner apparently doesn't plan to bring it back. It's definitely a shame to see it go.

If anybody wants better torrent handling, mr-orange's fork is probably the way to go now.

**Pull request closed without merging**
