### PR TITLE
Absolute Numbering Option for Series

### PR DESCRIPTION
**Pull request by tlusk**
Some TV series, namely Anime, are released using absolute numbers instead of season/episode.  Currently SickBeard does not support series that are released using this naming method.

This pull request includes an implementation of this feature, with proper file parsing, file renaming, metadata creation, and backlog searching.  It should be noted that the only provider this was fully tested on was nzbmatrix.  nzb.su does not seem to carry any anime so I could not test it on there, and i do not have a subscription to nzbs.org or newzbin.  Searching for episodes using those providers will either work, or return no results.

The parsing of shows using this naming scheme required the FileParser to use an entirely different set of regexs because shows named "Something 103" with the normal parser would mean season 1 episode 3.  So there is now a flag on the FileParser to parse as a normal show or an absolute numbered show.

The implementation of this is complex so feel free to comment and ask questions about anything.

[Sick-Beard showing off the new absolute numbering support with a backlog search](http://imgur.com/s9vFE.jpg)

[SABnzbd showing the extreme variance in Anime naming](http://imgur.com/VxsPi.jpg)

### CODE REVIEW

**Comment by midgetspy** [comment]
It is going to be at least a few days before I have a chance to actually review the code but I have a few questions that came to mind reading your summary:
- have you tested the httplib changes with no proxy (default config)?
- you mentioned that FileParser now has a flag to use absolute numbering. does this mean absolute numbering is a setting on the TVShow or something?

On nzbs.org and NZBMatrix there are a bunch of Bleach eps that are SxxEyy format... would these not get found anymore? What are some other shows like this other than Bleach? Also I see most Bleach eps are posted with names like [HorribleSubs] Bleach 123 which would get rejected by the current ep regex - is there a workaround for this?

Also I will have to give some thought to the quality change. The reason they are as restrictive as they are is to exclude formats that aren't desired. SB is intended to basically follow scene standards which means xvid or x264 only. With your 720p example the thing that immediately jumps to mind is 720p xvid or WMV... most people don't want that stuff but with your changes it'd get categorized as HD TV and downloaded. Of course like always the sore thumb here is NZBMatrix which is the only provider that doesn't sort that stuff itself.

If you can post a traceback of that encoding bug I can take a look, I probably broke it recently with my metadata changes.

**Comment by tlusk** [comment]
The proxy changes work fine with no proxy defined.  I run it on my server at home with no proxy but I wanted to work on this at lunch time at my office which uses an http proxy so it required me to make those changes in order to get communication.  So it doesn't affect users who don't have any proxy defined.

Yes, the absolute numbering is now a setting that is picked on a show, it is very similar to how air-by-date works, with a flag in the database that is configured on the edit screen defining if the show should use absolute numbering.  Setting this flag changes the display of all the episodes in the list to use the absolute episode values which are also stored in the database (fetched from tvdb).  It also changes the renaming to rename shows as "Series - ### - Desc".

If this setting is enabled it uses an entirely different series of regexs, so episodes that are actually named SxxEyy will not be matched.  Maybe there is a way to use the same set of regex but considering 203 could mean season 2 episode 3, or episode 203 that would be difficult.

Bleach was one of the main shows I was using to test this just because I know its still being released.  Another show I know about is "Fullmetal Alchemist: Brotherhood".  As for episodes released as "[ReleaseGroup] Series ###", those are handled by the absolute numbering regular expressions.

The quality change doesn't really affect these changes at all so its just something to consider.  Sadly you're correct on nzbmatrix, they don't seem to have a standard on the things posted especially in this category.  So everything gets marked as unknown even though a lot of them say 480p or 720p.  Ideally the best thing would be to specify both resolution and type and parse them separately but that's a large change.

Let me know if you have any other questions

**Comment by tlusk** [comment]
Here is the trace for the encoding bug you asked for.

```
  File "/usr/local/share/sickbeard_darkcube/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/usr/local/share/sickbeard_darkcube/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/share/sickbeard_darkcube/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/share/sickbeard_darkcube/sickbeard/webserve.py", line 1085, in processEpisode
    result = processTV.processDir(dir, nzbName)
  File "/usr/local/share/sickbeard_darkcube/sickbeard/processTV.py", line 204, in processDir
    result = processFile(movedFilePath, dirName, nzbName)
  File "/usr/local/share/sickbeard_darkcube/sickbeard/processTV.py", line 632, in processFile
    rootEp.createMetaFiles()
  File "/usr/local/share/sickbeard_darkcube/sickbeard/tv.py", line 1219, in createMetaFiles
    result = self.createNFO(force)
  File "/usr/local/share/sickbeard_darkcube/sickbeard/tv.py", line 1266, in createNFO
    result = sickbeard.metadata_generator.write_ep_file(self)
  File "/usr/local/share/sickbeard_darkcube/sickbeard/metadata/generic.py", line 177, in write_ep_file
    nfo_file = open(nfo_file_path, 'w')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 107: ordinal not in range(128)
```

**Comment by midgetspy** [comment]
About the regex, I know the episode regex will pick it up with the [Groupname] on it but I run all the search results through a second regex to make sure that they're actually the correct show (again this is because of NZBMatrix returning bad results). The regex makes sure that the result name starts with "Show Name" which will fail for "[GroupName] Bleach"... maybe there are enough releases that these missing ones aren't a problem?

**Comment by midgetspy** [comment]
About the encoding bug I believe I see the problem, I'll commit a fix later tonight.

**Comment by tlusk** [comment]
Ah yes, the regex in the sceneHelpers file.  This has been modified to ignore anything in [] before the series name if that exists. You can check the diff for the exact changes, but in order to support group names before the series name the following was added to the start of the regex.

```
(\[.+?\][ ])?
```

**Comment by tlusk** [comment]
Also a couple more things were added to accept lone numbers as episode numbers, because you currently expect either an e before the episode, or an x after the season.

```
(?:\d\d?\d?\s)|(?:\d\d?\d?$)
```

Those match on any number that either has white space after it, or is the end of the name.

**Comment by midgetspy** [comment]
I'm going to pull this into a branch so I can test it and keep it up to date there... feel free to keep pushing bug fixes or merging changes to your fork and I will pull from there.

**Comment by tlusk** [comment]
Sounds good, I'm just making cosmetic changes now and keeping it merged with the master.

**Comment by midgetspy** [comment]
OK I have thought about the quality thing and I think the way I want to handle it is to add a new quality: 720p Unknown. It would be the worst quality of the 720p ones, never selected by default. This would cover the cases you wanted handled, right?

**Comment by tlusk** [comment]
Sounds good

**Comment by midgetspy** [comment]
BTW after thinking about this feature I am now waiting on the name_parser branch which will simplify the way the names are parsed. Hopefully it won't be long, but if you want to break the HTTP Proxy stuff into its own branch I could merge that by itself.

**Comment by midgetspy** [comment]
OK name_parser is merged so I am going to start changing over your branch so I can merge with master. I noticed in TVShow.makeEpFromFile() you're using the TVDB API to convert absolute -> season/ep but elsewhere you use the database - is there a reason for this? Can we always use the database?

**Comment by tlusk** [comment]
I'll take a look at the merge tonight after work and let you know.

**Comment by tlusk** [comment]
I Performed a quick merge of the changes in the master branch with my branch. Need to do a bit more testing to make sure nothing broke.  I'll also look into the one section you said wasn't using the DB and see if there's a way I can use it instead of the tvdb api.

**Comment by midgetspy** [comment]
Ah great, I'd started doing that on my end so I'll merge your merge with my merge then :0)

**Comment by midgetspy** [comment]
I pulled your merge then added some fixes and committed them to my anime branch FYI

**Comment by tlusk** [comment]
Sounds good, I'll be looking at it more in the next couple days.  

I still found it necessary to add a flag to the FileParser noting if absolute numbering should be used when parsing the file name (due to the fact that 3 numbers has conflicting meanings, one being season and episode put together and the other being an episode that is 3 digits long).  If you have any solutions on how to solve that I'm all ears.

**Comment by tlusk** [comment]
I decided to approach the parsing in a different direction.  Instead of having a flag to tell the parser to look for normal episode numbers or absolute numbers, it now returns results for both.  It parses it normally and then it determines what the absolute numbers are based on if it found a season or not.  If a season was found, the season number is appended to the beginning of the episode number to create the absolute number.  If no season was found it assumes the numbers are already absolute.  Still bug testing this.

**Comment by tlusk** [comment]
Changes I made are working fine from my tests.  Haven't merged in anything since though. Haven't been looking at this much due to the holidays.

**Comment by tlusk** [comment]
new_config_v2 merged into this.  I like the new config screen changes that branch brought in :)

**Comment by jesscanady** [comment]
Has there been any activity on this? The last commit on the 'anime' branch was Dec 2010, and the last group of commits here is from Jan 2011.

**Comment by tlusk** [comment]
I try to keep my branch up to date with the latest so it can be merged in some day.  

The changes I wanted are complete, just awaiting the pull request.  The last time I updated the branch was late Match so I probably should merge master in sometime soon.

**Comment by mohagan** [comment]
praying this functionality gets added.

**Comment by thezoggy** [comment]
isnt this already in lad1337's anime branch with a lot more functionality?

**Comment by tlusk** [comment]
Possibly.  I haven't kept up with what he did.  He started his branch a while after this but I believe he added more providers.

**Comment by lad1337** [comment]
to be honest i only added one more provider fanzub.com
but additionally we have:
anidb.net file lookup if parsing fails
anidb.net mylist adding
sub group selection (black and white) per show ... group pool filled from anidb.net (incl automatic short name retrieval)
generic black and white filter per show
anime exceptions external and local exception list and automatic anidb.net main name adding
own quality parser for animes
and a pretty secure name parsing to not identity any normal episode file as anime
and maybe more ^^

**Comment by bjeanes** [comment]
+1

**Comment by jesscanady** [comment]
To be honest I've been using lad1337's fork for months now. It doesn't seem any less stable, and tracks upstream changes well. It's been fueling my wife's Naruto obsession no problem. If you need absolute numbering support, I recommend switching.

**Comment by tlusk** [comment]
I've been using my branch for almost a year now with no issues.  But It is much more limited compared to lad1337's branch because I was just trying to add generic support for series that are released in the absolute numbering format (Name - ###), and only really for nzbmatrix.  I tried to not put specific references to 'anime' in the code.

But after trying lad1337's branch over the past couple days it seems to work just as well and have more features.  I'm going to close this pull request in favor of his branch due to it being more feature rich.

Best of luck to you lad1337.

**Comment by lad1337** [comment]
wow ... thank you ... and if you have any suggestions feel free to contact me :)

**Comment by Mettbrot** [comment]
Why do you guys prefer using a different branch over merging the changes into the original code? I see no benefit in having two different branches...
I think support for absolute numbering would be a great addition to the sickbeard software, even for me who does not watch any anime...

**Comment by simonk83** [comment]
It's important to have a dev branch (think of it as a test/beta branch).
If it happens to break everything then it's not affecting the whole
userbase.

**Comment by Mettbrot** [comment]
If I got this right the anime branch is not the dev branch of sickbeard but a fork of it, containing extra features such as absolute numbering. Features which IMHO would be very usefull for sickbeard in general. So why do you rather support another different copy of the same software then working on integrating those features into original sickbeard?

**Comment by Mettbrot** [comment]
In Addition to that it seems that there has been no development in the anime branch for 7 months... Maybe @darkcube can take a look at this pull request again and see if it is possible to get it merged. It would be huuge :-)

**Comment by groenlid** [comment]
:+1:  to this as Sickbeard needs some way to support anime series and the last commit to the anime-fork was 10 months ago.

**Pull request closed without merging**
