### PR TITLE
update tvdb_api incl zip support

### PR DESCRIPTION
**Pull request by lad1337**
update to version 1.7.2 of https://github.com/dbr/tvdb_api

### CODE REVIEW

**Comment by arogl** [comment]
lad1337, having applied the update what else needs to be performed?

I have tried deleting the cache dir, with no effect.

The console shows the following error on startup:

Exception in thread SEARCHQUEUE-RSS-SEARCH:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 551, in **bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "E:\SickBeard\sickbeard\search_queue.py", line 126, in execute
    self._changeMissingEpisodes()
  File "E:\SickBeard\sickbeard\search_queue.py", line 162, in _changeMissingEpisodes
    ep = show.getEpisode(sqlEp["season"], sqlEp["episode"])
  File "E:\SickBeard\sickbeard\tv.py", line 154, in getEpisode
    ep = TVEpisode(self, season, episode)
  File "E:\SickBeard\sickbeard\tv.py", line 938, in __init**
    self.specifyEpisode(self.season, self.episode)
  File "E:\SickBeard\sickbeard\tv.py", line 1014, in specifyEpisode
    result = self.loadFromTVDB(season, episode)
  File "E:\SickBeard\sickbeard\tv.py", line 1094, in loadFromTVDB
    myEp = t[self.show.tvdbid][season][episode]
  File "E:\SickBeard\lib\tvdb_api\tvdb_api.py", line 841, in **getitem**
    self._getShowData(key, self.config['language'])
  File "E:\SickBeard\lib\tvdb_api\tvdb_api.py", line 797, in _getShowData
    epsEt = self._getetsrc( url, language=language)
  File "E:\SickBeard\lib\tvdb_api\tvdb_api.py", line 543, in _getetsrc
    src = self._loadUrl(url, language=language)
  File "E:\SickBeard\lib\tvdb_api\tvdb_api.py", line 535, in _loadUrl
    myzipfile = zipfile.ZipFile(zipdata)
  File "C:\Python27\lib\zipfile.py", line 714, in __init__
    self._GetContents()
  File "C:\Python27\lib\zipfile.py", line 748, in _GetContents
    self._RealGetContents()
  File "C:\Python27\lib\zipfile.py", line 763, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

The web interface shows:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "E:\SickBeard\cherrypy_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "E:\SickBeard\cherrypy\lib\encoding.py", line 193, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "E:\SickBeard\cherrypy_cpdispatch.py", line 25, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "E:\SickBeard\sickbeard\webserve.py", line 2020, in index
    return _munge(t)
  File "E:\SickBeard\sickbeard\webserve.py", line 120, in _munge
    return unicode(string).encode('utf-8', 'xmlcharrefreplace')
  File "C:\Python27\lib\site-packages\cheetah-2.4.4-py2.7.egg\Cheetah\Template.py", line 1010, in __unicode__
    return getattr(self, mainMethName)()
  File "_SickBeard_data_interfaces_default_home_tmpl.py", line 237, in respond
  File "E:\SickBeard\sickbeard\tv.py", line 708, in nextEpisode
    curEp = self.getEpisode(int(sqlEp["season"]), int(sqlEp["episode"]))
  File "E:\SickBeard\sickbeard\tv.py", line 154, in getEpisode
    ep = TVEpisode(self, season, episode)
  File "E:\SickBeard\sickbeard\tv.py", line 938, in __init__
    self.specifyEpisode(self.season, self.episode)
  File "E:\SickBeard\sickbeard\tv.py", line 1014, in specifyEpisode
    result = self.loadFromTVDB(season, episode)
  File "E:\SickBeard\sickbeard\tv.py", line 1094, in loadFromTVDB
    myEp = t[self.show.tvdbid][season][episode]
  File "E:\SickBeard\lib\tvdb_api\tvdb_api.py", line 841, in **getitem**
    self._getShowData(key, self.config['language'])
  File "E:\SickBeard\lib\tvdb_api\tvdb_api.py", line 797, in _getShowData
    epsEt = self._getetsrc( url, language=language)
  File "E:\SickBeard\lib\tvdb_api\tvdb_api.py", line 543, in _getetsrc
    src = self._loadUrl(url, language=language)
  File "E:\SickBeard\lib\tvdb_api\tvdb_api.py", line 535, in _loadUrl
    myzipfile = zipfile.ZipFile(zipdata)
  File "C:\Python27\lib\zipfile.py", line 714, in __init__
    self._GetContents()
  File "C:\Python27\lib\zipfile.py", line 748, in _GetContents
    self._RealGetContents()
  File "C:\Python27\lib\zipfile.py", line 763, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

**Comment by lad1337** [comment]
this just tells me that the tvdb has an issue serving zip files too

**Comment by arogl** [comment]
How can we set a pref to set useZip to True or False?

Or have the zip code fall back to normal on a zip download failure?

**Comment by midgetspy** [comment]
This is the same error that got reported when I pulled this last time... I guess we just need to handle it and possibly try again?

**Comment by thezoggy** [comment]
fyi there is an update to tvdb that should be included.. python 2.7.x and windows fix

**Comment by EchelonFour** [comment]
The recent updates don't fix this error (though they are needed for windows). https://github.com/dbr/tvdb_api/pull/26 fixes the BadZipfile exception.

**Comment by lad1337** [comment]
The mentioned pull 26 only catches the error but does nothing about it... No retry attempt or anything

**Comment by EchelonFour** [comment]
It raises the same error as if the request failed with zip disabled, that seems like the correct behaviour to me

**Comment by EchelonFour** [comment]
actually, i see what you mean. if you get a corrupt zip, it stays in the cache and every call after it is also corrupt until the cache is cleared

**Comment by thezoggy** [comment]
plz update of latest tvdb_api and try again. should have resolved our issues

**Comment by thezoggy** [comment]
@EchelonFour can you please test now off this latest update?

**Comment by thezoggy** [comment]
@arogl can you please pull down this latest update and test again ?

**Comment by EchelonFour** [comment]
i have been running this for a few days, and i cant say if connections to thetvdb.com are more stable, but the code works fine

**Comment by arogl** [comment]
Have just pulled this request and performed a few tests that failed previously. Will let you know if any errors occur. As @EchelonFour mentions thetvdb.com seems more stable.

**Comment by thezoggy** [comment]
@EchelonFour we only made the recent change 16 hours ago.. can you please update and try with the latest update

**Comment by EchelonFour** [comment]
@thezoggy I wrote those recent changes to tvdb_api myself a few days ago and have been running them since then. It all works fine

**Comment by thezoggy** [comment]
@EchelonFour okay cool. I see that itofzo also made some changes.. care to review (note that this does not have the most recent changes you made)?
https://github.com/itofzo/Sick-Beard/tree/tvdb_api_zip_dev_timeout

**Pull request merged**
