### PR TITLE
Untitled

### PR DESCRIPTION
**Pull request by andrewkhunn**
Changed body, #header, and .footer background-colors for user with small lists and large screen height.

### CODE REVIEW

**Comment by thezoggy** [comment]
just curious what this is targeted to fix?

**Comment by thezoggy** [comment]
can you post screen shots as well? i see that you changed the colors for the site as well

**Comment by andrewkhunn** [comment]
I changed only the background-color CSS for the body, #header and .footer classes. Not sure why the commit is saying I changed all 351 lines. I made this change so that the footer background-color stays off white even if the screen height is so large that the content can't fill it all. I think the screenshots will make it pretty apparent. Just look at the way the footer behaves in the updated version.

[Current CSS Definitions](http://files.andrewkhunn.com/pictures/Screen shot 2011-04-09 at 2.43.53 PM.png)

[Proposed Pull Definitions](http://files.andrewkhunn.com/pictures/Screen shot 2011-04-09 at 2.45.06 PM.png)

**Comment by Smenus** [comment]
I think the reason that the diff shows every line as having changed is the age-old issue of line endings.

The output from diff narrows it down to a few lines...

```
--- orig.txt    2011-04-10 13:59:33.000000000 +0100
+++ new.txt 2011-04-10 13:50:20.000000000 +0100
@@ -2,7 +2,7 @@
 img { border: 0; vertical-align: middle;}

 body {
-background-color:#fff;
+background-color: #f5f1e4;
 color:#000;
 font-family:'Verdana', 'Helvetica', 'Sans-serif', 'sans';
 font-size:12px;
@@ -36,6 +36,7 @@

 /* these are for incl_top.tmpl */
 #header {
+background-color: #fff;
 padding: 5px 0;
 z-index:2;
 }
@@ -126,7 +127,6 @@
 text-align:center;
 padding-top: 5px;
 padding-bottom: 5px;
-background-color:#F5F1E4;
 border-top:1px solid #b3b3b3;
 color:#4e4e4e;
 line-height: 1.4em;
```

**Comment by midgetspy** [comment]
Always check in with windows line endings, toggle your core.autocrlf if git is giving you issues.

**Comment by thezoggy** [comment]
this has been pulled.. just manually due to the line ending problem. it's in master branch now.

**Pull request closed without merging**
