### PR TITLE
Force line ending conversion on all files git considers text

### PR DESCRIPTION
**Pull request by mjc**
Putting "\* text=auto" in .gitattributes overrides the user's autocrlf option, so
regardless of what they have set, all text files will be converted to LF on
commit.

On checkout, git will convert all text files to the system's native line-endings
or to the one specified locally by the core.eol setting.

This is desireable because it will prevent mixed line endings, which make it
difficult for text editors, diff tools, and git to properly merge text,
regardless of whether the user has set their git configuration correctly or not.

### CODE REVIEW

**Comment by thezoggy** [comment]
whats the purpose of putting an option in .gitattributes but then yet rewriting half the folder... we will fix things as we come across.. rather than create all the uneeded noise

**Comment by mjc** [comment]
`git blame` has the `-w` option, which ignores whitespace changes.  Unfortunately neither github nor `git gui` have this option yet.

I use the alias `git b` for blame with ignore whitespace, like this:

```
mjc@DEV /d/apps/sickbeard (mjc_gitattribute-text-auto)
$ git config --global alias.b blame -w

# without ignore whitespace
mjc@DEV /d/apps/sickbeard (mjc_gitattribute-text-auto)
$ git blame -L 0,5 sickbeard/postProcessor.py
7dce166c (Michael J. Cohen 2012-10-03 16:55:00 -0400 1) # Author: Nic Wolfe <nic7dce166c (Michael J. Cohen 2012-10-03 16:55:00 -0400 2) # URL: http://code.googl7dce166c (Michael J. Cohen 2012-10-03 16:55:00 -0400 3) #
7dce166c (Michael J. Cohen 2012-10-03 16:55:00 -0400 4) # This file is part of S

# with ignore whitespace
mjc@DEV /d/apps/sickbeard (mjc_gitattribute-text-auto)
$ git b -L 0,5 sickbeard/postProcessor.py
7dce166c (Michael J. Cohen 2012-10-03 16:55:00 -0400 1) # Author: Nic Wolfe <nic7dce166c (Michael J. Cohen 2012-10-03 16:55:00 -0400 2) # URL: http://code.googl7dce166c (Michael J. Cohen 2012-10-03 16:55:00 -0400 3) #
7dce166c (Michael J. Cohen 2012-10-03 16:55:00 -0400 4) # This file is part of S7dce166c (Michael J. Cohen 2012-10-03 16:55:00 -0400 5) #
```

So there's at least a partial solution to this.

**Comment by thezoggy** [comment]
we recently talked about this in the jquery ui dev, some interesting notes:
https://github.com/jquery/jquery-ui/pull/743

and fyi, you can add `?w=1` to your github url to ignore whitespace on diff

**Comment by mjc** [comment]
The `?w=1` trick is neat, thanks for that.

**Comment by thezoggy** [comment]
you can leave this open if you want, havent had much time to check out pull requests lately. but adding the git attributes file will prob be smart.

**Pull request closed without merging**
