### PR TITLE
Torrent

### PR DESCRIPTION
**Pull request by mnestor**
I've added a custom Torrent Providers section and an option to the autoProcess to not do cleanup.

Tested with a torrent site running Template Shares for RSS feeds.

### CODE REVIEW

**Comment by thezoggy** [comment]
new code goes into development not master. also your commit history scares me. squash and clean up the history.

**Comment by mnestor** [comment]
I didn't know about squash I'm still new to git and I'm sure your commits are perfect everytime. No need to be insulting about it. Personally I like having a history of my saves so I know where I screwed up. Take the code or don't, I was just trying to share.

**Comment by thezoggy** [comment]
having a dirty history is fine locally, but when you are ready to submit code to be reviewed you should squash so its one commit per feature. as you are committing things and then undoing them.. it just creates a dirty history and makes it harder to follow. and if you dont think i was nice you need to grow some thicker skin.

**Comment by Skindred** [comment]
thezoggy is correct on this.

The end result you request to be pulled has to be one final set of changes.
Not a list of incrementals.

Your work howerver, is much apreciated!
Thank you!

**Comment by barnabyjones** [comment]
Hi @mnestor ,

I came here looking for a xspeeds provider for sickbeard - I see you removed the code you were working on as the customer provider works just as well. Could you point me to how to configure speeds with the customer provider?

Cheers

**Comment by mnestor** [comment]
@barnabyjones 
I just merged to master from midgetspy, you can pull it off my fork. It creates a "Configure Custom Torrent Providers" on the Search Providers page.

I'm still trying to figure out rebase so I can't make a pull request.

**Pull request closed without merging**
