### PR TITLE
Added DailyTvTorrents support

### PR DESCRIPTION
**Pull request by hvt**
I've added support for DailyTvTorrents [1]. I've found a preliminary patch by someone else here on Github, but I'm unable to find that repository again :S. If that somebody ever comes across, please let me know.

Furthermore, it's a real quick hack, that works for me, hopefully for someone else too.

[1] http://www.dailytvtorrents.org/

### CODE REVIEW

**Comment by midgetspy** [comment]
Woah, a torrent provider that supports backlog, nice!

The providers' XML parser has recently been changed from elementTree to minidom which will probably break this provider if it is passing or expecting eTree objects anywhere. You can see some examples of how to change from etree to minidom here: https://github.com/midgetspy/Sick-Beard/commit/97b2df7650e62622ba451389057ed9b02ae216a4

**Comment by hvt** [comment]
I'll be working on the minidom code sometime between now and next week :].

**Comment by arogl** [comment]
How does it handle exceptions e.g. "The River (2012)" has a feed of "the-river"?
Can we add such exceptions, or do we need to let DailyTvTorrents know?

**Comment by arabuli** [comment]
I don't know why but this is not working for me. When I try to launch it with python SickBeard.py it does nothing.

**Comment by hvt** [comment]
@arogl working on that, with some help :]

**Comment by arogl** [comment]
hvt, are you still working on this code?

**Comment by hvt** [comment]
No, most of my downloads are nzb based by now, so I haven't done any work on this anymore...

**Comment by thezoggy** [comment]
site is no longer, this can be closed:
`2013-04-25: Sorry guys, our hosting provider kicked us out so we have to be offline for now. I’m very busy nowadays and I don’t have time to look for a new place. If you think you know a solution you can reach me here: richard@dailytvtorrents.org.`

**Pull request closed without merging**
