### PR TITLE
More stable startup/shutdown

### PR DESCRIPTION
**Pull request by sestolk**
I could not get Sickbeard to start with the old version so I copied over the sabNZBd rc.d script and changed it so it works with Sickbeard. It now also retrieves the IP and Port from the config.

### CODE REVIEW

**Comment by thezoggy** [comment]
is this a dupe of https://github.com/midgetspy/Sick-Beard/pull/772 ?

**Comment by sestolk** [comment]
I have no idea, I ran into this problem a few days ago. Haven't looked through 130+ pull requests before I posted this. Ohwell, I might have a look at it tonight.

**Comment by thezoggy** [comment]
no worries, that pull just got pushed.. let us know if it fixes your problems... as i dont think anyone in sb dev runs sb on freebsd

**Comment by sestolk** [comment]
Shutting down actually works fine. I'm still a nooby at linux/freebsd, so I was confused that it worked. Then again, sabnzbd doesn't have an action in the init.d to shutdown either.

**Pull request closed without merging**
