### PR TITLE
Pushover configurable sound & device

### PR DESCRIPTION
**Pull request by gvdhoven**
Added (and tested) configurable sound & device for pushover.

### CODE REVIEW

**Comment by gvdhoven** [comment]
bump?

**Comment by thezoggy** [comment]
i just started on a new branch to cleanup a bit of our providers. i'll pull this branch into that so it gets included. i may need to ask to have you test that branch if thats okay

**Comment by gvdhoven** [comment]
Sure, no problem :)

**Comment by bazbjzy** [comment]
The Pushover API has a call you can make to get the current list of available sounds. I wonder if either that should be implemented here or if we should just offer a txtbox to the user to type in their desired sound. If Pushover changes it's sounds, we'll be out of sync since they're hardcoded here.

**Comment by gvdhoven** [comment]
That is a different notification provider

**Comment by thezoggy** [comment]
yes sorry, pushbullet vs pushover vs pushalot... so many android notifiers (all basically clones of each other)

seems like pushover and boxcar use the same sounds?
https://boxcar.uservoice.com/knowledgebase/articles/306788-how-to-send-your-boxcar-account-a-notification

**Comment by bazbjzy** [comment]
Until this gets pulled in, I've manually edited my pushover.py to add the sound I want...:
'sound': "intermission",

Is there any way for me to auto-update SickBeard but skipping the pushover.py file so I don't have to edit after each update?

Thanks!

**Comment by thezoggy** [comment]
this can be closed due to #886

**Pull request closed without merging**
