### PR TITLE
TorrentLeech provider

### PR DESCRIPTION
**Pull request by Grepsy**
This adds a TorrentLeech provider, based on RSS. The code is based on the TV Torrents implementation.

### CODE REVIEW

**Comment by piotrasd** [comment]
Hi, please add backlog like here
https://github.com/junalmeida/Sick-Beard/issues/9

Thanks ;)

**Comment by thezoggy** [comment]
all new code goes into development first. please rebase and target that branch.

**Comment by midgetspy** [comment]
Can you post an example of the contents that are on this RSS feed please? I don't have an account so I can't test it directly.

**Comment by midgetspy** [comment]
Fixed and merged.

**Comment by Grepsy** [comment]
Sample of RSS feed (I changed the urls to hide my key): 

https://gist.github.com/Grepsy/89fd5fbb51cc70ba7e84

**Comment by thezoggy** [comment]
seems like junalmedia's version is a little more evolved? as he stated his has backlog support..
https://github.com/junalmeida/Sick-Beard/blob/torrentProviders/sickbeard/providers/torrentleech.py

**Comment by junalmeida** [comment]
My version is scrapping TL site for torrent search and cache. I have some users reporting it's running fine, but my account was banned. Btw, didn't like this provider because all torrents are .rar and I disagree with this. Torrents are not meant to be zipped. It's a waste of local disk space.

**Comment by thezoggy** [comment]
so does this provider even work with torrent apps naively (uncertain if they accept rared torrents)?

**Comment by Grepsy** [comment]
I didn't know about @junalmeide provider, otherwise I wouldn't have written this. As it provides backlog support, it's a better candidate for inclusion in mainline (if it works correctly). Was there a pull request for that implementation before?

**Comment by junalmeida** [comment]
Yep it works with torrent apps via black hole method and direct method with utorrent, transmission and synology

**Pull request closed without merging**
