### PR TITLE
Added Banner Art to Show Display Page

### PR DESCRIPTION
**Pull request by bungiman**
I added banner art to the show display page. Nothing big, but looks nice. Cheers.

### CODE REVIEW

**Comment by thezoggy** [comment]
screenshot?

**Comment by bungiman** [comment]
This is how my change affects the display show page.

Change Screenshot

**Comment by camflan** [comment]
how does it work when the browser window width shrinks? I have a feeling it covers or goes under text, causing readability issues. You should add a css media query that shows that img only when the browser is over XXX pixels wide.

**Comment by bungiman** [comment]
camflan, I added fixes to address your problem. 1100px display minimum for the banner to be added. Cheers.

**Comment by camflan** [comment]
Nice :-)

**Comment by michaelficarra** [comment]
Very nice. **+1**!

**Comment by thezoggy** [comment]
hmm i'm not so diggin this

**Comment by lgordon** [comment]
I like it...

**Comment by BirdAPI** [comment]
+1

**Comment by bungiman** [comment]
thezoggy, would it be better if this was an option that could be enabled?

**Comment by thezoggy** [comment]
midget doesn't allow ui related options. so can count that idea as out :(

**Comment by pwr** [comment]
+1

**Comment by simonk83** [comment]
Looks good to me

**Comment by bungiman** [comment]
No interest in pulling this in. Closing. Bummer :(

**Comment by lgordon** [comment]
Too bad, I liked it too.

**Pull request closed without merging**
