### PR TITLE
BTJunkie Search Provider

### PR DESCRIPTION
**Pull request by cwc**
Added a provider to pull torrent search results from BTJunkie. The EZRSS provider was copied and tweaked to parse BTJunkie's RSS format.

### CODE REVIEW

**Comment by lopesdasilva** [comment]
How do Install this?

**Comment by cwc** [comment]
It helps to be familiar with Git, but you can try the instructions here: http://www.jetshred.com/2010/05/13/installing-sickbeard-on-mac-os-10-6/, using the URL for my repository (`git://github.com/cwc/Sick-Beard.git`) and making sure to switch to the 'btjunkie' branch (`git checkout btjunkie`).

**Comment by dryflood** [comment]
does anyone have any idea when this will make it to master?  I am currently pulling from CWC's repo but am now falling behind with the newest updates that have been comitted to midgetspy's master.

**Comment by cwc** [comment]
I intend to merge in the changes from origin when I get a chance. But I'm definitely hopeful that my changes make it into origin/master as
well. :)

**Comment by lopesdasilva** [comment]
my problem is that I use windows binaries :s

**Comment by dryflood** [comment]
Can you put a menu in the search providers GUI so the end user can stipulate the desired minimum quantity of seeds and maybe an option to tell it how old the torrent must be before snatching it?

Currently at least 11 of my 26 shows in sickbeard are downloading fakes nearly every week.  The torrentz seem to be quickly removed from btjunkie when fake so it would be good if I could say that the torrent must be at least 12 hours old etc.

Cheers
Gaz

**Comment by generica** [comment]
Have to say, if you've added support for a provider that puts up heaps of fake torrents, surely the answer isn't to then delay downloading by 12 hours.  The answer is to stop using this crappy provider.  Been using SB with usenet (as it was made to do) for almost a year now, and never ever has it downloaded a fake.

**Comment by cwc** [comment]
@dryflood: Yes, a way to configure the minimum seeds is the next thing I want to add. I hadn't thought of using the torrent's age; I'll have to look at btjunkie's xml to be sure that it's possible, but it sounds like a good idea. Thanks!

**Comment by dryflood** [comment]
Hi

Firstly, thanks for adding the minimum seed option.  Certainly helping me snatch some of the more obscure shows that the wife watches.

I am finding BTjunkie quite slow for putting up new content, I used to use torrentreactor.net they have an RSS search "http://www.torrentreactor.net/rss.php?search=desperate%20housewives%20s08e03" which works well and the timestamp that the torrent was added is correct unlike BtJunkie's so we could use the minimum age of the torrent to avoid fakes.

Could you find the time to make another search provider for sickbeard using torrentreactor?  It would certainly help out us guys using torrentz to have a couple of decent search providers.

Your work is greatly appreciated.

Cheers
Gaz

**Comment by cwc** [comment]
@dryflood: Thanks for the comment, I'm glad others are finding my changes useful. :) I'll definitely look into adding a Torrent Reactor provider.

In the meantime, I've already merged @dinoboy197's provider for KickassTorrents into my repo under the `torrentProviders` branch, so you might give that a try. I'll be adding any new providers to that branch as well; I'm actually considering "switching" this pull request to that branch, but am worried that the idea of merging a bunch of providers (as opposed to one at a time) would hurt the chances of any of the changes making it to `master`.

**Comment by cwc** [comment]
RIP BTJunkie.

**Pull request closed without merging**
