### PR TITLE
Added PLEX Compatible multi-ep. "Extend." Renaming style. (Updated)

### PR DESCRIPTION
**Pull request by chrisallen**
This adds support for a PLEX compatible multi-ep. extend. style.

### CODE REVIEW

**Comment by thezoggy** [comment]
perhaps you should squash these commits to make a cleaner history.

**Comment by chrisallen** [comment]
Cleaned up commit.

**Comment by chrisallen** [comment]
Any hope of having this commit added?

**Comment by ghost** [comment]
is there any chance to have this integrated?

**Comment by thezoggy** [comment]
sure when the custom_naming branch is done. it allows much greater flexibility on renaming files

**Comment by ghost** [comment]
great thanks for the hard work

**Comment by midgetspy** [comment]
Yeah no new naming configs will be added as the custom naming branch will support them all. That said if somebody wants to try the custom naming branch feel free, just make sure you back up your sickbeard.db/config.ini first.

**Pull request closed without merging**
