### PR TITLE
Added priority selecter for SABnzbd

### PR DESCRIPTION
**Pull request by adrianmoisey**
This allows you to set the priority of old (>7 days) and new episodes sent to sabnzbd. It may be useful for people who have more then just sickbeard pushing into SAB or for people like myself who run 2 sickbeards and want one of them to be a lower priority.

### CODE REVIEW

**Comment by adrianmoisey** [comment]
Is 2 a force?
No mention of it here: http://wiki.sabnzbd.org/api#toc36

**Comment by adrianmoisey** [comment]
I've added it as an option

**Comment by adrianmoisey** [comment]
Left to die I assume?

**Comment by adrianmoisey** [comment]
Done

**Comment by thezoggy** [comment]
if you want one to be lower you could just set the category you told sb to use.. to have a set priority rather than actually use the value passed from sb.

**Pull request closed without merging**
