### PR TITLE
1080i is HD (Issue 980)

### PR DESCRIPTION
**Pull request by josefwells**
http://code.google.com/p/sickbeard/issues/detail?id=980

In hopes that you will just add this since a Pull request is easier than looking at the code, or my crappy patch, or thinking too hard about 1080i vs other number/letter combinations.

### CODE REVIEW

**Comment by josefwells** [comment]
Also, thankyouthankyouthankyou*alot, sickbeard is totally awesome and simplifies my life, you are a superhero.

**Comment by kierr** [comment]
git noob here, has this been implemented? Or has someone else commited it to their fork?

**Comment by Smenus** [comment]
It's certainly not in master just yet, but it looks as easy as changing the `"1080p"` on line 137 to `"1080[pi]"`.

Edit: scratch that, as from my quick check 1080i is only ever ripped from TV, so line 137 isn't what's wanted. The change implemented by josefwells is probably the best place for it.

**Comment by thezoggy** [comment]
that line to rule out 1080i or 1080p from being picked up as sd

**Comment by midgetspy** [comment]
There's a different pull request that adds 1080i directly rather than making it 1080p, closing this.

**Pull request closed without merging**
