### PR TITLE
Changes to allow for 1080p WEB-DLs

### PR DESCRIPTION
**Pull request by aaronflorey**
Allow users to download 1080p WEB-DL releases, as they are now going to be released regularly.

### CODE REVIEW

**Comment by Amelandbor** [comment]
This would be great to have. For updating the db you have to add a class to maindb.py if I read the code correctly.

**Comment by thezoggy** [comment]
https://gist.github.com/3854795

**Comment by pokonski** [comment]
So it's just a matter of modifying the "quality" column in the "history" SQLite table?

**Comment by thezoggy** [comment]
thats one piece of the puzzle.. other is the ep composite quality.. can see where im at with it so far: http://sickbeard.com/forums/viewtopic.php?f=8&t=5188&start=30#p24646

**Comment by pokonski** [comment]
Sweet, will test your branch :)

**Comment by thezoggy** [comment]
This pull request should be closed. as Pull #564 is what should be used

**Pull request closed without merging**
