### PR TITLE
Change to https://github.com when used with urllib2.urlopen

### PR DESCRIPTION
**Pull request by ghost**
Starting point was a line in the log: 'CHECKVERSION :: Unable to contact github, can't check for update'
Doing a 'git pull' in the sickbeard folder via terminal, worked everytime.

'versionChecker' is using functions from lib/pygithub/github.py to extract SickBeard version,
using the github api to extract data.

So tried rebuilding the API url.
Something like: http://github.com/api/v2/xml/commits/list/midgetspy/sick-beard/master
and dropped the url in a browser to see what happens. 

When accessing http://github.com the url gets redirected to https.

So tested with a little script and found that using a http:/github.com url
( like 'http://github.com/midgetspy/Sick-Beard/tarball/master') in 
Urllib2.urlopen intermittently results in
Errno 104 (linux)/ Errno 10054 (windows) Connection reset by peer 
or success.

Using the https://github.com url in Urllib2.urlopen doesn't have this problem.

### CODE REVIEW

**Comment by xombiemp** [comment]
Awesome!  I was getting really sick of the 'CHECKVERSION :: Unable to contact github, can't check for update' errors in the log.

**Comment by Guuz** [comment]
Bump! We need this in fast!

ps. maybe we should upgrade to the latest version of the lib? https://github.com/dustin/py-github

**Comment by thezoggy** [comment]
i did some recon on the lib situation in sb a few months back.. midget is not keen on upgrading libs just for the sake of updating.. as some libs were modified for sb's purposes.. thus upgrading would cause a bit of extra work just to get things working again.

dateutil                https://github.com/kfdm/gntp
    current:    1.5 (and latest for python 2.x)

gntp/growl              https://github.com/kfdm/gntp
    current:    0.1 (from 2009)
    latest:     0.5 (released Nov 2011)

httplib2                http://code.google.com/p/httplib2/
    current:    0.6.x (released Dec 2009) 
    latest:     0.7.2 (released 2011-11-14)

oauth2                  https://github.com/simplegeo/python-oauth2
    current:    from ~2009
    latest:     b211 (released 2011-12-13)

pygithub                https://github.com/dustin/py-github
    current:    ~2008
    latest:     (commited on 2011-11-04)

pythontwitter           http://code.google.com/p/python-twitter/
    current:    0.8-devel (from 2010-10-16 i think)
    latest:     0.8.2 (released 2011-04-16)

simplejson              https://github.com/simplejson/simplejson
    current:    2.0.9 (released 2009-02-18)
    latest:     2.3.2 (released 2011-12-30)

socks (SocksiPy)        http://socksipy.sourceforge.net/
    current:    1.0
    latest:     1.0 (2006-10-25 ) -- source is documented/has more code than our version

tvdb_api                https://github.com/dbr/tvdb_api
    why do we have tvrage_api / tvnamer / tvdb_api all in the same folder?
    tvdb_api latest:     (commited on 2011-10-22)

**Comment by Smenus** [comment]
As far as socksipy goes, there's a later version (still tagged as 1.00, but with modification) available with httplib2, which I've changed to in my 'proxy_fix' branch.
I'm 99% certain that my change won't have caused any issues, but I haven't submitted a pull request because I hadn't heard of anyone else with the same problems I'd had.

**Pull request merged**
