### PR TITLE
Add support for JRiver Media Center metadata.

### PR DESCRIPTION
**Pull request by sgomes**
This adds support for metadata generation for JRiver Media Center: http://www.jriver.com/index.html

### CODE REVIEW

**Comment by sgomes** [comment]
Actually, I'll improve this in the next few days by adding support for dates too.

**Comment by sgomes** [comment]
Alright, all ready for pulling :)

**Comment by sgomes** [comment]
Any updates on this? I'd love to see JRiver Media Center support in the official release

**Comment by thezoggy** [comment]
should rebase and squash commits, also use the development branch for your base

**Pull request closed without merging**
