### PR TITLE
update btn api url

### PR DESCRIPTION
**Pull request by heylookltsme**
Updates the api url for BTN. Does what https://github.com/midgetspy/Sick-Beard/pull/982 does, but without the line ending changes. 

The BTN forums have threads full of folks hacking this fix. I just did it myself with success. It'd be great to have it in officially. Thanks!

### CODE REVIEW

**Comment by heylookltsme** [comment]
Hang on, I just looked more closely at the activity on the repo... is sickbeard actively maintained anymore? 😿

**Comment by CyberMew** [comment]
Unfortunately no, most of us are on Sonarr now

**Comment by heylookltsme** [comment]
Thanks! Gonna check that out.

**Comment by TVViewer** [comment]
Please can we get this merged it's such a tiny simple thing that would save many users a lot of hassle

**Comment by JackDandy** [comment]
> are on Sonarr now  

Many alternatively migrated their existing Sick-Beard set up to [SickGear](https://github.com/SickGear/SickGear/wiki/Installation-Instructions) -- actively developed since 2014 :-)

**Comment by thezoggy** [comment]
sickbeard itself has been abandon ware for quite some time..  most people left for one of the sickbeard forks (sickrage/sickrage ce/sickgear/etc) or for sonarr. do youself a favor and switch..

**Pull request closed without merging**
