### PR TITLE
Made checks for x264, h264, h.264 more liberally matching

### PR DESCRIPTION
**Pull request by sirchia**
I required these modifications to the quality checkers to be able to download 'The legend of Korra' using NZBMatrix as a search provider.

### CODE REVIEW

**Comment by thezoggy** [comment]
this seems a little messy.. and if its only nzbmatrix with the issue.. why not modify the nzbmatrix provider? also, plz submit against the development branch as all new code goes into there first.

**Comment by sirchia** [comment]
It has nothing to do with nzbmatrix as provider as the quality 'guesstimation' is done based on the name of the NZB spot/post which is just how some indivdual/release group decides to name it (e.g. "The Legend Of Korra S01E07 The Aftermath 720p HDTV h264 OOO"). There is no world-wide standard defining the format of this name, and if there was, there is no guarantee that everyone adheres to that standard (the posts of The legend of Korra on nzbmatrix being proof of that). 

In order to get the correct quality matching (HDTV in the example) the regular expression used was to restrictive, hence my proposal to improve it.

I recreated the branch with my modifications from the development branch.

**Comment by thezoggy** [comment]
can you close this pull then, its gotten a bit out of control :)

**Comment by midgetspy** [comment]
Yep I dunno what this started as but if it is still needed please re-submit.

**Pull request closed without merging**
