### PR TITLE
Synology's NAS integration

### PR DESCRIPTION
**Pull request by zebulon501**
Provide the option to notify the media indexer of the Synology's NAS at the end of the post processing.

### CODE REVIEW

**Comment by midgetspy** [comment]
What exactly does this synoindex do?

**Comment by Diaoul** [comment]
Indexing multimedia content on Synology NAS. I think it is used to share medias through protocols like DLNA.

Hi zebulon, you here :)

**Comment by zebulon501** [comment]
synoindex -a adds the file to the internal database of the UPnP MediaServer embedded into the NAS. Doing so avoid the long process of a full re-indexing of the file system. synoindex is a proprietary software from Synology, as its name suggests.

**Comment by zebulon501** [comment]
@midgetspy: is there any decision about this feature? Is there any thing I need to change to get it pulled?

**Comment by midgetspy** [comment]
Nope I've just been busy with the SB Index - I'll pull it soon.

**Comment by midgetspy** [comment]
FYI in the future you should always work inside a branch and keep your master clean and synced.

**Comment by zebulon501** [comment]
Thanks for the pull! and thanks for the git advice, was my first use of git, I'm used to more traditional VC (cvs, cvs, p4).

**Pull request merged**
