### PR TITLE
Subtitles support

### PR DESCRIPTION
**Pull request by Diaoul**
Here is my first contribution to add subtitles support to Sick-Beard using [my own fork of periscope](https://github.com/Diaoul/periscope-ng):
- Configuration page with CSS, icons and js
- Subtitles download at post-process time
- Download subtitles button in the show page
- Subtitles download in "Manage" page for mass editing
- Subtitles download on a regular basis on its own thread (or not? not sure yet)

You can choose to bring periscope into Sick-Beard, like other libraries. But I think I'm gonna make some more changes in periscope-ng.
### Warning:

If you have periscope installed (the original project), this will interfere and replace it with my version.
Periscope-ng requires python module BeautifulSoup >= 3.2.0. If you are a Ubuntu Natty user, you can install it with your Synaptic.
### Steps:
1. `git clone git://github.com/Diaoul/periscope-ng.git`
2. `cd periscope-ng`
3. `sudo python setup.py install`

### CODE REVIEW

**Comment by tester22** [comment]
Great work but why not add Periscope-ng to the lib folder, this would aviod any interference with users that already have periscope installed.

**Comment by Diaoul** [comment]
Because I leave the choice of implementation up to midgetspy. I think that putting periscope-ng as a lib is a good idea too.
Periscope-ng works on it's own as a module and I want to keep it's development separated from Sick-Beard's development until I release a final stable version of periscope-ng.

Edit: Missclicked on "Comment and close" -_-

**Comment by Technicolour** [comment]
I think this is an amazing idea, as I'm guessing it will tie the subtitles to the file on download? Meaning that once you have the files downloaded and renamed you don't have to guess what subtitle version to get?

**Comment by Diaoul** [comment]
Actually, it attempts to download subtitles at post processing.
Anyway, it is possible that no subtitles are found so I made possible to re-launch it in the show page and mass edit page (manage menu).
Depending on plugins used, periscope can use :
- A hash of the video file (OpenSubtitles, TheSubDB)
- Guessed data from filename (for web-scrapping plugins and some others)

The last point can be improved and I'm working on using a robust library for filenames parsing as Patrick Dessales for periscope/periscope-ng.

**Comment by zebulon501** [comment]
Hey, is there any update on this pull request? It would be very nice to be able to automatically download subtitles along the episodes.

**Comment by Diaoul** [comment]
I'll do some implementing work on my own this week:
Put everything in lib to have a "all-in-one" Sick-Beard with Subtitles support, no need to install periscope-ng on your own as it'll be provided with Sick-Beard (in the lib folder, as suggested by tester22)
Also, I'm going to improve periscope-ng a little bit:
- Use [guessit](http://pypi.python.org/pypi/guessit/) as parsing library for filenames within periscope-ng
- Fix some subtitles providers

Anyway, this pull request is still valid as it is working like a charm, maybe I'll make another one later with the "all-in-one" fork.

**Comment by Diaoul** [comment]
I finished my work on periscope-ng.
I'll make another pull request later with this "new" periscope-ng

**Pull request closed without merging**
