### PR TITLE
Episode title mistaken for additional episode

### PR DESCRIPTION
**Pull request by ghost**
I encountered a problem while re-scanning files:
the_walking_dead-s04e01-30_days_without_an_accident.mp4 was mistaken for season 4 episoden 1 through 30...

### CODE REVIEW

**Comment by thezoggy** [comment]
that is a badly named file. not supported by sickbeard. E##-## is format for multi-ep. so not a bug.. just badly named file.

**Comment by thezoggy** [comment]
additionally. new code would go into the development branch not master. this should be closed.

**Comment by ghost** [comment]
Maybe the log speaks for itself:

2013-10-18 23:24:58 INFO     CP Server Thread-5 :: Analyzing name u'The.Walking.Dead.S04E01.mp4'
...
2013-10-18 23:24:58 DEBUG    CP Server Thread-5 :: formatting pattern: %s_n-s%0Se%0E-%e_n -> the_walking_dead-s04e01-30_days_w ithout_an_accident

**Comment by ghost** [comment]
I changed my custom name pattern to a preset one but also tested the other preset name patterns. My bad, sorry for wasting your time. :-(

**Comment by thezoggy** [comment]
`formatting pattern: %s_n-s%0Se%0E-%e_n` that pattern is invalid. sickbeard shouldnt let you save the config with it. as you would run into this exact issue. we added the logic to stop this from happening a few months ago (to catch ep#-epname) if you use something other than - as the deliminator or put spaces/something to break up the pattern then it would be fine.

**Pull request closed without merging**
