### PR TITLE
Issue 1629: Add new directories to Synology index

### PR DESCRIPTION
**Pull request by Botono**
When a new show is added (and the respective directory created), add the new directory to the Synology index.

### CODE REVIEW

**Comment by mreid-tt** [comment]
Hi, thanks for your input with this... I did however get around to submitting a new pull request #591 which was merged with the development branch recently. We are now awaiting synchronization into the master.

**Comment by Botono** [comment]
Ah, good show. Must have overlooked that one. Any reason the post processor
doesn't use the helper methods?

**Comment by mreid-tt** [comment]
Couldn't say, I hope that eventually all the I/O operations would be passed to the helper methods to make things easier. It was something I suggested since I made the first pull request (#208).

**Comment by mreid-tt** [comment]
@Botono: I note that my pull request was recently merged with the master. Can you update your version and test to see if this has resolved the issue?

**Comment by Botono** [comment]
I can test it this evening.

**Comment by Botono** [comment]
I tested adding a new show and it correctly added the new folder to the Synology index.

**Comment by mreid-tt** [comment]
great! thanks for the testing @Botono, then I'll leave you to close this pull request...

**Comment by Botono** [comment]
Roger.

**Pull request closed without merging**
