### PR TITLE
FIX: Keep original file doesn't keep reprocessing and nofiying the same ...

### PR DESCRIPTION
**Pull request by acasajus**
...file again and again

Fixes http://code.google.com/p/sickbeard/issues/detail?id=1538 and http://sickbeard.com/forums/viewtopic.php?f=6&t=848

### CODE REVIEW

**Comment by thezoggy** [comment]
so you wanna add code to 'fix' people with bad configurations?

**Comment by acasajus** [comment]
It happens to most people downloading with torrents. If you check the url's, people are solving this problem using custom scripts. 

What's the 'good' configuration that prevents this behaviour?

**Comment by lad1337** [comment]
doing this helps:
http://code.google.com/p/sickbeard/issues/detail?id=1538#c1

does you fix still work with initial and archive ? question is does the initial download status contain downloaded if so this will break it

i would sugest blocking it on a config/gui lvl ... not allowing "scan folder" and "keep originals"

**Comment by acasajus** [comment]
Reading the comment also helps

> I unchecked 'Keep Original Files' and the endless notifications stopped, but SB should be able to handle this scenario for the people who (for whatever reason) actually want to keep the original files.

For instance, to keep seeding the torrent after it has been downloaded and processed.

**Comment by midgetspy** [comment]
Ideally you shouldn't be post processing the folder where your torrents are seeding from but you should have your torrent client copy completed downloads to a "finished" folder that SB can process.

**Comment by acasajus** [comment]
The problem with doing that is that the torrent client is not "sickbeard exclusive" people use their torrent clients for more stuff than just sickbeard. If I do that then ALL the stuff the torrent client is downloading will be copied and only the stuff that sickbeard knows about will be moved somewhere else. Anything that sickbeard doesn't know about will be duplicated and I'll have to manually remove it. By post-processing the seeding folder I don't have to clean up manually the sickbeard post processing folder.

**Comment by acasajus** [comment]
any more comments?

**Comment by cgriffin4** [comment]
A fix to this problem would be extremely helpful.  It looks like my options at this point are to manually copy the files to a folder that SickBeard processes, have SickBeard post-process constantly, or not seed.  None of these options are considerably good.

**Comment by acasajus** [comment]
Just get the changes from my branch

**Comment by cgriffin4** [comment]
@acasajus Thanks, that would work.  If the official release isn't patched I will be forced to do that, I was hoping to avoid it since I'm not familiar with the process of compiling into a package my Synology NAS will install.

**Comment by midgetspy** [comment]
This would mean that replacing episodes with higher qualities would no longer work, so I can't merge this.

**Comment by acasajus** [comment]
With a minor modification I think I can also check if the quality is the same or worse. Would you accept it then?

**Pull request closed without merging**
