### PR TITLE
display all seasons

### PR DESCRIPTION
**Pull request by thezoggy**
Fix display_all_seasons config saving and default it to on, and just let people turn it off if they want.

### CODE REVIEW

**Comment by david-chappelle** [comment]
How to undo this?  Showing all seasons is horrible for shows with a lot of episodes like talk shows.

**Comment by thezoggy** [comment]
just toggle the display all seasons variable via config or in your sb, config/hidden page. showing all seasons isnt horrible for everyone... just those that have slow cpu/hdd :)

**Comment by david-chappelle** [comment]
I tried editing config.ini and restarting SB, but it overwrites my change on startup.  Is there a way to change within the SB UI?  What file do I need to edit?

Showing all seasons with shows over 1000 episodes is very slow, and I really don't care who was the guest for Jon Stewart in February of 2008, anyway...

**Comment by Stanzilla** [comment]
@sub0ptimal go your webinterface and append /config/hidden/ to the url.

**Comment by thezoggy** [comment]
or just modify config.ini when sb isnt running. since sb reads/writes ini on start/quit.

**Comment by david-chappelle** [comment]
@thezoggy @Stanzilla Thanks much, was not aware config.ini got re-written on exit.

**Pull request merged**
