### PR TITLE
Super Toasty Notifier

### PR DESCRIPTION
**Pull request by Technicolour**
Adds in support for the WP7 push notifier super toasty

### CODE REVIEW

**Comment by exiva** [comment]
Nice work!

**Comment by Technicolour** [comment]
Thanks :) Sorry to have taken your contribution ;)

**Comment by exiva** [comment]
No problems! I had a small issue with getting the image to work (Was using a post not a get. whoops.) and nothing to test on since device was in repair.

**Comment by exiva** [comment]
Any chance of this being pulled soon?

**Comment by mxhob1** [comment]
+1 for this, would love to see it be pulled into master

**Comment by thezoggy** [comment]
needs to be rebased and squashed commits off development branch.. as some things have changed since this was submitted.

**Comment by exiva** [comment]
#507 has all the requirements met.

**Comment by quacker1982** [comment]
Would love to see this added to the master

**Comment by thezoggy** [comment]
close in lieu of #507

**Pull request closed without merging**
