### PR TITLE
Email notifications

### PR DESCRIPTION
**Pull request by ivanfilippov**
Working implementation of email notifications on non-secure SMTP server. Addresses Google Code issue  #1911 (http://code.google.com/p/sickbeard/issues/detail?id=1191)

### CODE REVIEW

**Comment by ghost** [comment]
Please implement this!

**Comment by icovada** [comment]
Magnificent, exactly what I was looking for.
Let us not forget good old email

**Comment by xombiemp** [comment]
Does this work using Gmail as the SMTP server?  I'm guessing not because you state "on non-secure SMTP server".

**Comment by ivanfilippov** [comment]
It doesn't work on servers with SSL/TLS security like the ones Gmail provides. It should be trivial to add if this ever gets merged.

**Comment by xombiemp** [comment]
You should add it now!  I would love to see this get merged, and I think you'll have a better chance if it supports SSL/TLS.

**Comment by ivanfilippov** [comment]
Good point xombiemp, I'll try to have a look at this next week, as I'm a bit busy for the next little while.

**Comment by gregsheremeta** [comment]
This is still open? 2 years?

**Comment by ivanfilippov** [comment]
Pretty sure this functionality was implemented between 2011 and 2016. Closing PR.

**Pull request closed without merging**
