### PR TITLE
Added ability to choose custom Pushover sound

### PR DESCRIPTION
**Pull request by bazbjzy**
Pushover API provides for the selection of alternate sounds. Without this option, sickbeard sounds no different than my home automation system telling me my front door is open. If the user types an invalid sound the default Pushover sound is used.

Pushover API info:
https://pushover.net/api#sounds

### CODE REVIEW

**Comment by thezoggy** [comment]
Pushover config sound and device -- https://github.com/midgetspy/Sick-Beard/pull/779

**Comment by bazbjzy** [comment]
Guess I should have searched better :). Oh well, thx for referencing them.

**Comment by thezoggy** [comment]
no worries. i have it slated to be included in an upcoming update.. just have to wait for a previous update to make it into dev first

**Comment by bazbjzy** [comment]
Looks like it's being handled elsewhere

**Pull request closed without merging**
