### PR TITLE
Generate PyTiVo metadata with Sickbeard

### PR DESCRIPTION
**Pull request by gordonturner**
Implemented enhancement request, issue 795 Generate PyTiVo metadata with Sickbeard:

http://code.google.com/p/sickbeard/issues/detail?id=795

Has been tested by myself and at least one other user.  Please let me know if you have any feedback or required changes.

### CODE REVIEW

**Comment by midgetspy** [comment]
FYI in the future always develop in a branch and keep your master clean.

**Comment by midgetspy** [comment]
Please pull my "tivo" branch and make sure that my merge + changes worked correctly, then I'll merge to master.

**Comment by gordonturner** [comment]
K, I am used to cvs/svn, still sorting out git and best practices, thanks for the tip.

The commented out code is not required for basic tivo metadata functionality (i.e. for the shows to be pulled / pushed to the tivo and be grouped correctly).  I just included them so that the placeholders were there, will complete the rest of them shortly.

Working on validating merge+changes today.

**Comment by gordonturner** [comment]
I have completed testing on the tivo branch, implemented vActor and corrected vGenre, minor formatting and tested output.

All ready to be merged into the master.

**Comment by gordonturner** [comment]
https://github.com/gordonturner/Sick-Beard/tree/tivo

**Comment by midgetspy** [comment]
Pulled, thanks!

**Pull request closed without merging**
