### PR TITLE
adds notnot notifier

### PR DESCRIPTION
**Pull request by sejo**
Signed-off-by: Jochen Maes jochen@sejo-it.be

### CODE REVIEW

**Comment by thezoggy** [comment]
could you squash your commits and force push so we have a cleaner commit history and less likely hood of merge conflicts. also, is notnot free?

**Comment by sejo** [comment]
notnot is totally free, no paying for the app, nor for the service.

I squashed and force pushed.

jochen

----- Original Message -----

> From: "thezoggy" notifications@github.com
> To: "midgetspy/Sick-Beard" Sick-Beard@noreply.github.com
> Cc: "Jochen Maes" jochen@sejo-it.be
> Sent: Thursday, February 21, 2013 6:18:37 AM
> Subject: Re: [Sick-Beard] adds notnot notifier (#573)
> 
> could you squash your commits and force push so we have a cleaner
> commit history and less likely hood of merge conflicts. also, is
> notnot free?
> 
> —
> Reply to this email directly or view it on GitHub .
> 
> could you squash your commits and force push so we have a cleaner
> commit history and less likely hood of merge conflicts. also, is
> notnot free?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/midgetspy/Sick-Beard/pull/573#issuecomment-13873616

## 

SeJo IT BVBA
Lange Akker  23
9240  Zele
http://sejo-it.be/
+32 474 04 38  19
"ne humanus crede"

**Comment by thezoggy** [comment]
ty, ill see if we can get this included in this round of updates :)

**Comment by midgetspy** [comment]
The notifier links to https://notnot.sejo-it.be/ which is currently serving up 500's, I'll have to test later when it's up again.

**Comment by sejo** [comment]
Sorry,

I just switched datacenter with my servers. Everything is back up and should be running.

Jochen

----- Original Message -----

> From: "Nic Wolfe" notifications@github.com
> To: "midgetspy/Sick-Beard" Sick-Beard@noreply.github.com
> Cc: "Jochen Maes" jochen@sejo-it.be
> Sent: Saturday, February 23, 2013 8:04:45 PM
> Subject: Re: [Sick-Beard] adds notnot notifier (#573)
> 
> The notifier links to https://notnot.sejo-it.be/ which is currently
> serving up 500's, I'll have to test later when it's up again.
> 
> —
> Reply to this email directly or view it on GitHub .
> 
> The notifier links to https://notnot.sejo-it.be/ which is currently
> serving up 500's, I'll have to test later when it's up again.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/midgetspy/Sick-Beard/pull/573#issuecomment-13995465

## 

SeJo IT BVBA
Lange Akker  23
9240  Zele
http://sejo-it.be/
+32 474 04 38  19
"ne humanus crede"

**Comment by sejo** [comment]
Any progress?

**Comment by sejo** [comment]
shutdown Not Not service

**Comment by JackDandy** [comment]
@sejo
This project is no longer active, perhaps try [SickGear](https://github.com/SickGear/SickGear) - you can drop in your existing sickbeard.db and continue with more features, search performance improvements and modern UI.

**Pull request closed without merging**
