### PR TITLE
re-add hdbits support, update to development branch

### PR DESCRIPTION
**Pull request by georgewhewell**
update #477 to development branch

### CODE REVIEW

**Comment by georgewhewell** [comment]
Any change of this being merged?

**Comment by thezoggy** [comment]
can you squash your commits for a cleaner commit history. does this work on python 2.5 ?

**Comment by georgewhewell** [comment]
Squashed. Yep, works on 2.5 so long as simplejson is available.

**Comment by zain** [comment]
Bumping this. Would be great to get this in.

**Comment by thezoggy** [comment]
can you rebase this and update where needed. We just re-wrote all the providers backend and updated some things for torrents..

**Comment by georgewhewell** [comment]
rebased. doesn't appear to require any changes

**Comment by ghost** [comment]
Started working on some changes: https://github.com/itofzo/Sick-Beard/commits/pre_fix_add_change_hdbits_provider_dev
Basically fix json import and add check missing/ wrong credentials

Can someone provide the hdbits api 'manual' for non members (not a link to the hdbits website)?

Not sure if findEpisode should be removed or changed.

Is or isn't it possible to search for episodes via api?
Menu Config > Search Providers: Provider does not support backlog searches at this time
suggests it doesn't, but it looks like findEpisode suggests it can.

**Pull request merged**
