### PR TITLE
Header is always visible

### PR DESCRIPTION
**Pull request by enriquemorenotent**
Sometimes for long running tv shows, the page can get too long. I thought its a good idea to have the menu always visible :)

### CODE REVIEW

**Comment by thezoggy** [comment]
i do not like this. this defeats the purpose of using stickyHeaders in the table or the fact we have a 'jump to top' in the bottom right when the menu is not visible. plz do NOT pull this

**Comment by enriquemorenotent** [comment]
Agreed, with this the use of the top button becomes irrelevant.

What is stickyHeaders? I didnt see this option in the configuration screen.

**Comment by bungiman** [comment]
Can you post a screenshot?

**Comment by thezoggy** [comment]
http://zoggy.net/sb-upgrades3.png

**Comment by bungiman** [comment]
I actually like this. What if you add another row above it for edit/submit buttons too? Then the user would have access to submission always too,

**Comment by enriquemorenotent** [comment]
That screenshot is not really what it should do... weird. Can you post a full-page screenshot. so I can check what is going on?

**Comment by thezoggy** [comment]
the screenshot shows what the stickyheaders does.. why i think your pull request and this current feature would be a train wreck.

**Comment by bungiman** [comment]
Sorry, I think I got confused. thezoggy, the SS you posted was of stickyheaders? How is that enabled? 

If what I saw was _not_ added functionality from this pull request, then I think this should be closed.

**Comment by enriquemorenotent** [comment]
@bungiman you think it should be closed? You dont even know what this pull request does! :D

**Comment by bungiman** [comment]
Yeah, that is part of the reason though :P Can _you_, the author, please post a screenshot of what is supposed to be going on?

**Comment by enriquemorenotent** [comment]
There you go :) http://goo.gl/ZQ0y2

**Comment by bungiman** [comment]
Thank you :) So personally, I don't mind it. In fact it could be useful and makes navigation feel like a typical program where your "state-changing" stuff is at the top. With that being said I think you should make sure it does the following.
1. Plays well with stickyheader, since it is already in the codebase.
2. Since it makes the "Top" link completely irrelevant, you should remove that too.

If 1&2 are done, then I would probably pull it into my fork and vote that it go into the main branch.

**Comment by thezoggy** [comment]
fyo, this pull request destroys the ability to use sb on a mobile or small resolution.

**Comment by bungiman** [comment]
@thezoggy css media queries should fix that though.

@enriquemorenotent I guess media queries becomes task 3 on the list.

**Pull request closed without merging**
