### PR TITLE
Stopped sickbeard from renaming original files.

### PR DESCRIPTION
**Pull request by AWilco**
Recent changes meant sickbeard altered the file name of original files. This breaks Torrent seeding programs because they lose the file. This modification combines the renaming and moving/copying steps to minimise file system changes and keeping the original file name.

### CODE REVIEW

**Comment by midgetspy** [comment]
There were a number of bugs with this, I pulled and fixed whatever I noticed but I haven't tested it at all - it's in my "working" branch atm.

**Comment by rascalli** [comment]
Testing the working branch , but it seems renaming is still done : 

Parsed /storage1/incoming/tv_test/Supernatural.S05E22.BDRip.XviD-SAiNTS/Supernatural.S05E22.BDRip.XviD-SAiNTS.avi into Supernatural - S5E22 - BDRip.XviD (SAiNTS)

Or is this not caused by this commit ???

**Comment by rascalli** [comment]
Tested the working branch & works OK.

Only this part can confuse people , as it looks like SB is renaming .. but it does not do that : Parsed /storage1/incoming/tv_test/Supernatural.S05E22.BDRip.XviD-SAiNTS/Supernatural.S05E22.BDRip.XviD-SAiNTS.avi into Supernatural - S5E22 - BDRip.XviD (SAiNTS)

**Comment by midgetspy** [comment]
Thanks rascalli - this is pulled to master now.

**Pull request closed without merging**
