### PR TITLE
Implementation of pyTivo notification

### PR DESCRIPTION
**Pull request by gordonturner**
Notifier for pyTivo to allow automatic uploading of shows to a TiVo.  Requires a working install of pyTivo.

### CODE REVIEW

**Comment by kbgators** [comment]
Thanks for all your work!

**Comment by thezoggy** [comment]
not sure why you modified boxcar and trakt lines...

**Comment by gordonturner** [comment]
@thezoggy End of line character change, side effect of using Lion FileMerge tool.

@kbgators Thanks!

**Comment by gordonturner** [comment]
Is there anything else I can do to get this accepted into Sick-Beard?

**Comment by Diaoul** [comment]
Wait more

**Comment by gordonturner** [comment]
FYI, this should resolve:  

http://code.google.com/p/sickbeard/issues/detail?id=1615

**Comment by thezoggy** [comment]
does this work with: http://www.theverge.com/2012/1/20/2720292/tivo-premiere-software-update-now-available-for-everybody ?

**Comment by gordonturner** [comment]
Don't have a Premiere to test with, so don't know what the update has changed.

Hopefully they wouldn't break the HMO and GoBack server functionality.

This notifier calls pytivo which is based on TiVo's own upload functionality used by their desktop software.

**Comment by Nobrumski** [comment]
The TiVo update has changed the way some metadata is handled on the Premiere but PyTiVo still works fine with the update. Also the main fork of PyTiVo is updated pretty consistently, https://github.com/wmcbrine/pytivo

**Comment by lwpack** [comment]
When is this going to get into Sickbeard? I don't understand the reluctance to incorporate this.  For those of us with a Tivo, this is much needed functionality.

**Comment by kbgators** [comment]
yes, same question here.  Just waiting.

**Comment by midgetspy** [comment]
Bad line endings are currently preventing this from being pulled automatically - I would have to pull, fix it myself, and then test which I Haven't had time to do.

**Comment by gordonturner** [comment]
K, didn't realize the line endings were preventing automatic pull, will correct tomorrow.

**Comment by gordonturner** [comment]
Had a family emergency over the weekend, will try and fix this asap.

**Comment by kbgators** [comment]
Thanks. Btw this is working with my TiVo Premier

**Comment by gordonturner** [comment]
New pull request here: https://github.com/midgetspy/Sick-Beard/pull/291

**Pull request closed without merging**
