### PR TITLE
Issue 1629: Add full Synology index command set (addendum)

### PR DESCRIPTION
**Pull request by mreid-tt**
This amends the previous pull request #208 which added the complete 'synoindex' command library to Sick-Beard. The specific fix is to include the notifier for the creation of a new TV show.

### CODE REVIEW

**Comment by mreid-tt** [comment]
Any idea when you guys might get around to pushing this?

**Comment by mreid-tt** [comment]
It seems that somewhere in the mix some of the original code from pull request #208 (specifically the trigger to add folders) seems to have been lost. Rather than creating a convoluted mess (plus I don't know exactly when my original code got lost - maybe in the switch to merging from the development branch), I'm going to withdraw this request and submit a new one combining both needs.

**Comment by Roeland54** [comment]
You didn't submit a new request. Are you still working on a solution? It would be very helpful and it looks you are pretty close.

**Comment by mreid-tt** [comment]
Yes, this is true... I wrote to the author the following note some months ago with no response:

I previously submitted some code under pull request #208 for which some of it is no longer in the current master. Additionally based on my observation that you seem to be moving toward my suggestion of having the I/O functions executed in the abstract 'helpers' function, the addendum pull request #430 now no longer seems sensible (so I cancelled it).

I also note you have code in the helpers to determine if a file is media or not as well as a lot of new code in the post processor for moving files. Now the synoindex has all these functions included in the notifier I coded in pull request #208 but I need some guidance from you as to how I should attempt to reintegrate this into the project. Shall I now be considering all addendum to the helpers funtion only? It just seems to me that you are not complete with this transition (for example I see system function calls to create folders both in the postprocessor directly and called from there to the helpers).

I would like some guidance on how I can fix the now broken Synology code for folder handling or alternately, should I wait for a few more revisions for the project to use the helpers function for all I/O and then try to fix it?

**Comment by mreid-tt** [comment]
Okay, I took the time to do a quick patch and submitted as pull request #591. Hopefully it will get merged soon... Be sure to comment in the new pull request to give it some attention.

**Pull request closed without merging**
