### PR TITLE
Add notifier that executes custom command when episode is added to library

### PR DESCRIPTION
**Pull request by Remboooo**
This plugin enables the execution of a custom command (as the sickbeard user) when an episode file is added to the library, to allow for easy scripting of custom actions (I use it for notifications on IRC and notifying a custom Android app, for example).

There are ofcourse security risks involved; that's why this plugin won't work without the user explicitly editing a line in config.ini. This is clearly stated, including the risks involved, on the configuration page.

On the to-do list would be adding the ability to execute custom commands on other types of events, as well as customizing the (order of) the command-line arguments.

### CODE REVIEW

**Comment by thezoggy** [comment]
new code should be based off development not master. also you should squash your commits for the same feature. also this looks eerie similar to the extra_scripts notifier i started

**Comment by Remboooo** [comment]
I have fixed the issues with the pull request and made them into a single commit into a new branch in my fork, based on the development branch:
https://github.com/Remboooo/Sick-Beard/commit/cc8b320024734ddb4b3f7ffdf9693f4bb74fd96f

Being fairly new to github, I'm not entirely sure how to modify this pull request (or do I just start a new one and close this one?)

Now that you mentioned the extra_scripts parameter I googled it and found the option, I guess that makes this plugin fairly redundant. However it might be nice to have something a bit more visible to the user browsing through the configuration pages looking for this option. The downside is the security issue, although the user is made well aware of it.

I also noticed the extra_scripts parameter also passes a few additional parameters to the script that mine doesn't (e.g. tvdb id).

Well, the code is there for you to take into consideration, I won't be mad if it doesn't make it into the official Sickbeard master branch ;)

**Comment by thezoggy** [comment]
id say just close this one and submit your new branch...  ill have to go dig up my notes on how i wanted the extra_scripts notifier to work but i'll deff look into this

**Comment by Remboooo** [comment]
https://github.com/midgetspy/Sick-Beard/pull/604 should be the corrected new pull request.

**Pull request closed without merging**
