### PR TITLE
SickBeard UI - html5

### PR DESCRIPTION
**Pull request by thezoggy**

### CODE REVIEW

**Comment by myusuf3** [comment]
I would love to see a screenshot of how this looks if possible.

**Comment by piejanssens** [comment]
Looking good!

**Comment by thezoggy** [comment]
there is a ton of small fixes.. most of the changes are to markup/css. changing out jquery ui for bootstrap. then the other changes are just updating images for a cleaner look. 

here are two images that i took earlier during the dev process, slightly changed since then.. but you will get the idea

http://zoggy.net/sb-bootstrap1.png
http://zoggy.net/sb-bootstrap2.png

**Comment by myusuf3** [comment]
:+1:

**Comment by SemperFu** [comment]
Those icons look much cleaner. Nice job.

**Comment by ghost** [comment]
May I suggest that you squash your commits? The git log are not being treated with respect :P

**Comment by thezoggy** [comment]
The commits are already squashed to down to a per feature/change. This makes dealing with merging a bit easier as this is going into the dev branch with other branches such as custom_naming. If it was only one commit for the massive change it would be a pain to track down and deal with conflicts as it's `Showing 149 changed files with 7,059 additions and 2,183 deletions.`.

**Comment by piejanssens** [comment]
Why is this not accepted yet?

**Comment by thezoggy** [comment]
due to recent changes, i had to rebase and fix conflicts. also updated some other libs.. resubmitting new pull request

**Pull request closed without merging**
