### PR TITLE
Failed download handling

### PR DESCRIPTION
**Pull request by TFenby**
Creates a new db to track releases that fail to download properly, and adds a page to the UI for viewing/managing that database. Checks to make sure potential downloads are not in that database.

Requires that "Post-Process Only Verified Jobs" be disabled in SABnzbd.

### CODE REVIEW

**Comment by TFenby** [comment]
Warning to those who used my previous patches: you need to manually edit your sickbeard.db and remove the 'failed' column from the history table and decrement the db_version by one. (Or just set the version. The extra column _shouldn't_ hurt, but you never know.)

```
sqlite sickbeard.db
update db_version set db_version=11;
```

**Comment by Kwebbel** [comment]
Hi Tolstyak,

Is it possible to trigger a episode.search after a failed download so the next available version will be downloaded directly?

**Comment by TFenby** [comment]
It should be picked up pretty quick by the search thread.

**Comment by mistorx6767** [comment]
Long time coder, fairly new to sickbeard and xbmc, really excited to try this out, so I've got your code, I've followed the usual upgrade instructions (http://code.google.com/p/sickbeard/wiki/HowToUpgradeSickBeard), restarted and see your new menu options, and I've disabled "Post-Process Only Verified Jobs" in SABnzbd.  Job fails on the sab side and then I don't see anything in the logs on the sickbeard side, nothing the failed.db, any pointers?  Running SAB 0.7.3 on ubuntu.

**Comment by TFenby** [comment]
Did you set up sabToSickBeard under autoProcessTV?

**Comment by Clem-H-Fandango1** [comment]
Hi there - having the same trouble as mistorx above - sab and sickbeard have been working fine together for a while in my setup - ie sab calling sickbeard via sabtosickbeard.exe, renaming, moving etc.  I've now got your version running and can see the new Failed Downloads option under Manage. A download fails in sab, but nothing appears in Sickbeard's log.  The failed download sits in my TV directory.  The log in sab says:

http://192.168.0.2:8089/home/postprocess/processEpisode?nzbName=NAMEOFSHOW.nzb&quiet=1&dir=F%3A%5CDownloads%5CTV%NAMEOFSHOW

<html>

```
<head>

    <title>404</title>

    <script type="text/javascript" charset="utf-8">

      <!--

      location.href = "/"

      //-->

    </script>

</head>

<body>

    <br/>

</body>
```

</html>

nzb name changed to NAMEOFSHOW above

Any ideas?  I feel I am close but what am I missing..

Many thanks

**Comment by TFenby** [comment]
404 means page not found. Post the contents of your autoProcessTV.cfg file (without the password line, of course).

Edit: Actually, go here: https://github.com/Tolstyak/Sick-Beard/issues
Let's keep the comments here clean.

**Comment by Clem-H-Fandango1** [comment]
no problemo

moved here https://github.com/Tolstyak/Sick-Beard/issues/5

**Comment by mistorx6767** [comment]
Yes, I've set up sabtosickbeard, I can see it kick in properly for downloads which work.

2013-02-18 00:03:15,390::INFO::[postproc:344] unpack_magic finished on The.Walking.Dead.S03E10.720p.HDTV.x264-EVOLVE
2013-02-18 00:03:15,391::INFO::[newsunpack:137] Running external script /home/mike/.sickbeard/autoProcessTV/sabToSickBeard.py(/home/mike/Downloads/complete/The.Walking.Dead.S03E10.720p.HDTV.x264-EVOLVE, The.Walking.Dead.S03E10.720p.HDTV.x264-EVOLVE.nzb, The.Walking.Dead.S03E10.720p.HDTV.x264-EVOLVE, , tv, alt.binaries.teevee, 0)

Looking through my sab logs for a show I know will fail I can see:

2013-02-18 14:19:59,484::INFO::[postproc:280] Starting PostProcessing on TBBT.S06E11.The.Santa.Simulation.720p.WEB-DL.DD5.1.H.264 => Repair:False, Unpack:False, Delete:True, Script:sabToSickBeard.py, Cat:tv

No where after that do I see running external script like I do on the successful download.  I do however see the following semi suspicious entries:

2013-02-18 14:19:59,489::DEBUG::[growler:169] Cannot register with Growl [Errno 111] Connection refused

2013-02-18 14:20:00,178::INFO::[misc:1263] Cannot remove folder /home/mike/Downloads/incomplete/TBBT.S06E11.The.Santa.Simulation.720p.WEB-DL.DD5.1.H.264.1/**ADMIN**

I can forward full sab logs if that would be helpful.

"Post-Process Only Verified Jobs" is disabled.

Sab side shows "Download failed - Out of your server's retention?"

Sickbeard logs show nothing after "Sending NZB to SABnzbd".

**Comment by TFenby** [comment]
Move that over to an issue at https://github.com/Tolstyak/Sick-Beard/issues

**Comment by mistorx6767** [comment]
Moved to https://github.com/Tolstyak/Sick-Beard/issues/6

**Comment by bandrel** [comment]
It is probably because unpack is set to false.  SB needs the files to be
unrared first

Yes, I've set up sabtosickbeard, I can see it kick in properly for
downloads which work.

2013-02-18 00:03:15,390::INFO::[postproc:344] unpack_magic finished on
The.Walking.Dead.S03E10.720p.HDTV.x264-EVOLVE
2013-02-18 00:03:15,391::INFO::[newsunpack:137] Running external script
/home/mike/.sickbeard/autoProcessTV/sabToSickBeard.py(/home/mike/Downloads/complete/The.Walking.Dead.S03E10.720p.HDTV.x264-EVOLVE,
The.Walking.Dead.S03E10.720p.HDTV.x264-EVOLVE.nzb,
The.Walking.Dead.S03E10.720p.HDTV.x264-EVOLVE, , tv, alt.binaries.teevee, 0)

Looking through my sab logs for a show I know will fail I can see:

2013-02-18 14:19:59,484::INFO::[postproc:280] Starting PostProcessing on
TBBT.S06E11.The.Santa.Simulation.720p.WEB-DL.DD5.1.H.264 => Repair:False,
Unpack:False, Delete:True, Script:sabToSickBeard.py, Cat:tv

No where after that do I see running external script like I do on the
successful download. I do however see the following semi suspicious entries:

2013-02-18 14:19:59,489::DEBUG::[growler:169] Cannot register with Growl
[Errno 111] Connection refused

2013-02-18 14:20:00,178::INFO::[misc:1263] Cannot remove folder
/home/mike/Downloads/incomplete/TBBT.S06E11.The.Santa.Simulation.720p.WEB-DL.DD5.1.H.264.1/**ADMIN**

I can forward full sab logs if that would be helpful.

"Post-Process Only Verified Jobs" is disabled.

Sab side shows "Download failed - Out of your server's retention?"

Sickbeard logs show nothing after "Sending NZB to SABnzbd".

—
Reply to this email directly or view it on
GitHubhttps://github.com/midgetspy/Sick-Beard/pull/579#issuecomment-13739602.

**Comment by TFenby** [comment]
@bandrel - Wrong place.

**Comment by schumi2004** [comment]
Is this PR depreciated or is it merged in mainstream?

**Comment by TFenby** [comment]
Don't feel like maintaining a separate branch. If they decide they want to merge in just the failed download handling parts, I can cherry-pick a new branch for them. and open a PR with it.

**Comment by Skindred** [comment]
Has this been submitted to Mr-Orange's fork yet?
If not, please do so, Mr-Orange incorporates many of these really good PR's.

**Comment by schumi2004** [comment]
I'm already running it on my dutch-tpb branch from Mr-orange fork but it's better tolstyak submits it himself

**Comment by TFenby** [comment]
@Skindred - I didn't know about it. I'll check it out.

**Comment by wolph** [comment]
For the record, here's the link to Mr-Orange his fork: https://github.com/mr-orange/Sick-Beard

Not sure if that fork gets pull requests merged more often but if not I'm thinking of having my own public Sick-Beard repo since some pull requests (like this one) have been open for about 4 years already... I understand that the guys are busy but if you don't have enough time, hand it over to someone who does have enough time.

**Comment by Kwebbel** [comment]
I agree completely with WoLpH. I'm running Tolstyak his fork for some time now and its great. Just like CP this, and also other great stuff that was written, should have been merged into the official sickbeard repo a long time ago.

**Comment by ausey00** [comment]
Is there a way for us to shoe-horn this feature into the current build of sickbeard? I'm tired of having to manually configure failed NZB's...

**Comment by TFenby** [comment]
I do keep my branch up to date with MidgetSpy's.

**Comment by simonk83** [comment]
Hi Tyler, could you remind me of the link to your fork?   I'm going to have to switch, this IMO is an essential feature and I can't do without it anymore.    I don't suppose you have the timezone pull merged into yours as well?  I think I might be in heaven if that's the case :D

**Comment by TFenby** [comment]
https://github.com/Tolstyak/Sick-Beard

Link me to the timezone one and I'll check it out. I already have a patch or two pulled into my development-custom branch from the island of misfit patches.

**Comment by simonk83** [comment]
Nice, thanks.

Here's the timezone pull:  https://github.com/midgetspy/Sick-Beard/pull/635

Prinz seems to be pretty on the ball with it :)

**Comment by ausey00** [comment]
Apologies, I'm a bit new to github :) I'm going to get reading on how I go about doing this, hopefully I can get upgrade the install on my unRAID system.

**Comment by simonk83** [comment]
Ok, got it up and running.   Is there anything that needs to be done (aside from disabling the option in SAB), or is it all just automatic?    I just need to wait for something to fail I guess to see if it works :D

**Comment by TFenby** [comment]
Only other thing you need to do is open SABnzbd, go to Config, Switches, and uncheck "Post-Process Only Verified Jobs".

**Comment by ausey00** [comment]
Beat me to it Simon! Just installed it. What is the option in SAB I'm supposed to disable?

**Comment by TFenby** [comment]
"Post-Process Only Verified Jobs"

**Comment by ausey00** [comment]
That's the only change to make to enable failed job handling?
EDIT: It's working, many thanks Tolstyak!

**Comment by itsmarkw** [comment]
Ausey, did you do anything special to get it running on Unraid? I thought I had it running, but it's behaving exactly the same with failed downloads.

**Comment by wolph** [comment]
If you have the modified version of sickbeard, don't forget to change the sabnzbd switches as explained in Tolstyak's readme.

**Comment by itsmarkw** [comment]
Thanks Wolph, I did change those switches, it isn't working though. I'm pretty sure it's something unique to Unraid.

**Comment by TFenby** [comment]
Open a ticket and we can try to get it figured out. https://github.com/Tolstyak/Sick-Beard/issues

**Comment by itsmarkw** [comment]
Thanks Tolstyak, I'm pretty sure it's a problem with my installation rather than a problem on your end. I'll see if I can figure it out when I get some time, if it looks like it's the software itself rather than me screwing up the installation, I'll open a ticket. Otherwise, if I get it figured out I'll post how I did it in case other Unraid users are curious. Or if Ausey gets a chance, I'd love to hear how he got it working.

**Comment by bigjohns97** [comment]
I have an episode that has previously failed and i can't get sickbeard to try to download it again, is there anyway to force a retry of the same download?

**Comment by TFenby** [comment]
Delete it from the list of failed downloads under Manage > Failed Downloads. Also, issues/questions should open a ticket against my repo.

**Pull request closed without merging**
