### PR TITLE
Prowl support.

### PR DESCRIPTION
**Pull request by tester22**
Figured out how to branch the proper way so here is the branch with prowl support.

### CODE REVIEW

**Comment by anothergene** [comment]
I'll give it a try with tvt.

**Comment by tester22** [comment]
anothergene: couldn't recreate your prowl error even on a fresh install to a new folder. Could you send me your config.ini file?

**Comment by anothergene** [comment]
Sorry tester, I had two instances of sickbeard running on the same port.  I guess one didn't quit gracefully.  I love the prowl notifications!

**Comment by midgetspy** [comment]
Your prowl branch still has the tvtorrents stuff in it it looks like?

**Comment by tester22** [comment]
Forgot that, sorry. Will fix this evening.

**Pull request closed without merging**
