### PR TITLE
Coming Eps Minimal

### PR DESCRIPTION
**Pull request by Smenus**
This adds a view to the Coming Episodes tab with no plot or information other than the poster or banner.
This will be familiar if you've used MediaFrontPage with the minimal.css style. Unfortunately, due to changes in SB, it's not as simple anymore, so I've added the option directly.
Screenshots are [here (posters)](http://cl.ly/2p3D2t0E3B291E0F2h2p) and [here (banners)](http://cl.ly/2B0q3D1n2J1B1X1I2O3a). There's a new toggle next to Show Paused, all modifications working fine here.

### CODE REVIEW

**Comment by elmarkou** [comment]
After Update It will not show the real banner and poster images. Only a sickbeard image.

**Comment by thezoggy** [comment]
holly crap i wish i found this earlier. i have a 'similar' style modification to the coming ep that i think will make you quite happy. http://www.sickbeard.com/forums/viewtopic.php?f=8&t=1451&p=6585#p6585

**Comment by Smenus** [comment]
@thezoggy, awesome! I've gotta say, I much prefer your modifications; they're always a lot cleaner than mine, and this is no exception. I love the way you've done the tooltips - it took me over an hour to figure out how to show a super basic one! I'll close this pull request, as I hope yours will be in soon.

**Comment by ghost** [comment]
@thezoggy: Looking great!

**Pull request closed without merging**
