### PR TITLE
Update init.freebsd

### PR DESCRIPTION
**Pull request by LukeChannings**
Fix for shutdown issue on FreeBSD.

### CODE REVIEW

**Comment by thezoggy** [comment]
can you check out pull #807 and see if this resolves your issue?

**Comment by LukeChannings** [comment]
The init script references in #807 doesn't hang on shutdown, but it does fail to delete the .pid file if FreeBSD is restarted with SickBeard running, which causes SickBeard to fail to start on boot.

**Comment by mraspberry** [comment]
What version of FreeBSD are you using? I tested #807 on a jail of FreeBSD 10.0-RELEASE and it worked correctly.

**Comment by josh4trunks** [comment]
I recommend you guys stop controlling sickbeard using wget. it responds correctly to the SIG-TERM that the freebsd rc.subr system uses. there is no need to write such complicated functions with unneeded dependencies. also... what freebsd user uses wget over fetch for such a simple task?! =P

you can use my ports init, you need to change the %%VARS%% that are replaced during port make.
https://github.com/josh4trunks/freenas-plugins/blob/master/ports/multimedia/sickbeard/files/sickbeard.in

**Pull request closed without merging**
