### PR TITLE
Untitled

### PR DESCRIPTION
**Pull request by adam-bielicki**
it seems all (I couldn't find an exception amongst my shows) episodes appearing with airdate 'never' are airing after episodes with a defined airdate in the future. They should be excluded from the progress bar on home as they are unavailable.

### CODE REVIEW

**Comment by adam-bielicki** [comment]
see the current commits. This should work properly.

**Comment by adam-bielicki** [comment]
any word on these changes?

**Comment by midgetspy** [comment]
I didn't notice you updated this... I'll pull this tonight.

**Comment by midgetspy** [comment]
Should be in now.

**Pull request closed without merging**
