### PR TITLE
kat.ph torrent support

### PR DESCRIPTION
**Pull request by junalmeida**
This is a provider to support http://kat.ph torrents. I'm testing it for 7 months and it proves to be very valuable on snatching quality torrents for my tv shows.

### CODE REVIEW

**Comment by cagnulein** [comment]
There's a conflict in kickass icon. You're using 'png' in code, but you've uploaded a 'gif' ;)

**Comment by thezoggy** [comment]
should squash commits and force-push

**Comment by midgetspy** [comment]
Yeah please rebase/squash this into a new branch off current master and I will pull it in, thanks.

**Comment by midgetspy** [comment]
This provider returns HTML files for me. I have an updated version in my katph branch but I am closing this request for now.

**Comment by junalmeida** [comment]
The kat.ph changed its service recently. I'm working on a fix.

Att,
Marcos Almeida Jr.
http://about.me/junalmeida
Enviado do meu Android.
On Apr 29, 2012 7:41 PM, "Nic Wolfe" <
reply@reply.github.com>
wrote:

**Comment by junalmeida** [comment]
Fix commited.

**Comment by thezoggy** [comment]
can you squash your commits so your history isn't so ugly? also you really should just rebase if you havent pushed it out to be pulled.. so you dont cause those ugly resyncing off master entries

**Comment by thezoggy** [comment]
also, you shouldnt work in master but in a branch.. keep things cleaner :)

**Comment by junalmeida** [comment]
moved from master to "torrentProviders" branch

**Comment by gurmukhp** [comment]
Looks like they may have changed it again (and also torrentz), would you be able to do another fix?

thanks

**Comment by junalmeida** [comment]
Hi!

Just pushed a fix of the kickass provider. Fetch origin :) 

Torrentz was working normally for me. If it is still buggy for you, show me the logs.

Thanks :)

Att,
Marcos Almeida Jr.
http://about.me/junalmeida

**Comment by gurmukhp** [comment]
Perfect, thank you very much :)

On 4 August 2012 04:21, Marcos Junior <
reply@reply.github.com

**Comment by gurmukhp** [comment]
I think kat might have changed their site again :(

**Pull request closed without merging**
