### PR TITLE
A unittest environment for Sickbeard

### PR DESCRIPTION
**Pull request by lad1337**
a test "library" for some parts of sickbeard
and some very basic tests
this is no ta full implemented test bench but is a great start for one
can create a temporary db where fake data can be enternd...
and setup some sickbeard globals / fake them... etc

it is intended to test only in very small cases and not a whole running sickbeard
try it by running all_tests.py :)

i hope this can help at some point

ps only new files added nothing in the sb code is changed
pps yes the test_combos test fails

### CODE REVIEW

**Comment by thezoggy** [comment]
lad, can you run this through pylint/pep8 along with rebasing off master since this is 4 months old?

**Comment by lad1337** [comment]
due to the rebase i had to force push ... but diffs look good

**Comment by Diaoul** [comment]
Not sure the rebase is the good way to catch up with midgetspy's changes. A forced push is always a bad thing IMO. I use http://help.github.com/fork-a-repo/ : merge with upstream

**Comment by lad1337** [comment]
rebase is a good way ... force = bad i know .... but these are all new files nothing "old" touched ... if still in question i can file a pull request on https://github.com/lad1337/Sick-Beard/tree/unittest_rebase

the rebase just gives a cleaner / clearer history ... e.g. all my changes are on top ... like patches

**Comment by thezoggy** [comment]
a rebase is good for non public branches (this branch doesnt have any forks) as you have to use --force.. and if midget for example rebased his public branch and forced the changes.. all of our forks would be detached basically and would crap on themselves. we recommend people to rebase their branches to resync with master as it saves the 'pull with master' clutter when/if they get merged with master. this also keeps the branches commits to the top as it rewrites the history.

*\* just notice that lad already pretty much said everything.

**Comment by lad1337** [comment]
nm

**Comment by thezoggy** [comment]
why close this? not worth having?

**Pull request closed without merging**
