### PR TITLE
Added support for displaying the last time this show was updated from TVDB

### PR DESCRIPTION
**Pull request by kjoconnor**
Added support for displaying the last time this show was updated from TVDB
Requires the following schema changes:

ALTER TABLE tv_shows ADD COLUMN updatetime NUMERIC;

This corresponds to http://code.google.com/p/sickbeard/issues/detail?id=886

### CODE REVIEW

**Comment by lad1337** [comment]
why dont you add the table altering to mainDB.py ?

**Comment by arogl** [comment]
The following updates may be required for new users:

data/interfaces/default/displayShow.tmpl @ line 87

```
-    <td><td class="showLegend">Last Update Time:</td><td>$datetime.datetime.fromtimestamp(int($show.updatetime)).strftime('%Y-%m-%d %H:%M:%S')</td></tr>
+    <td><td class="showLegend">Last Update Time:</td><td>$datetime.datetime.fromtimestamp(int($show.updatetime)).strftime('%Y-%m-%d %H:%M:%S')</td></tr>
```

Changes the first td on the line to a tr

sickbeard/tv.py @ line 532

```
-                self.updatetime = sqlResults[0]["lang"]
+                self.updatetime = sqlResults[0]["updatetime"]
```

Changes the default update to 0, rather than the current language setting, in my case en.

Rgds Andrew.

**Comment by thezoggy** [comment]
can we get this rebased off the current master? this is a bit out of date now...

**Comment by kjoconnor** [comment]
@thezoggy do I submit a brand new pull request or just update the commits on this one?

**Comment by kjoconnor** [comment]
I just opened a new one - https://github.com/midgetspy/Sick-Beard/pull/256

**Comment by thezoggy** [comment]
you could have just rebased/updated this branch and it would have been reflected here. but new pull works too. :)

**Comment by kjoconnor** [comment]
It was so old and messy I just figured this might be easier!

**Pull request closed without merging**
